package com.stockit.backend.feature.strategy.approval;

/** 최종 선택 직전 다시 확인한 실행 조건의 변경 유형. */
public enum StrategyExecutionConditionChangeType {
    AVAILABLE_QUANTITY_DECREASED,
    INVENTORY_UNAVAILABLE,
    LOT_NOT_SELLABLE,
    INVENTORY_LOCATION_CHANGED,
    START_DATE_PASSED,
    SELLABLE_END_DATE_CHANGED,
    SALES_POINT_INACTIVE,
    TRANSFER_ROUTE_UNAVAILABLE,
    UNIT_COST_CHANGED,
    SELLING_PRICE_CHANGED,
    PAYMENT_FEE_CHANGED,
    LOGISTICS_COST_CHANGED,
    MINIMUM_SELLING_PRICE_VIOLATED,
    TRANSFER_INPUT_CHANGED
}
