DROP ALL OBJECTS;

CREATE TABLE strategy_case (
    strategy_case_id NUMBER PRIMARY KEY,
    sku_id NUMBER,
    case_status VARCHAR2(30),
    is_deleted NUMBER(1)
);

CREATE TABLE strategy_option (
    strategy_option_id NUMBER PRIMARY KEY,
    strategy_case_id NUMBER,
    is_deleted NUMBER(1)
);

CREATE TABLE final_strategy_selection (
    final_selection_id NUMBER PRIMARY KEY,
    strategy_case_id NUMBER,
    strategy_option_id NUMBER,
    created_by NUMBER,
    is_deleted NUMBER(1)
);

CREATE TABLE strategy_execution_result (
    strategy_execution_result_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    final_selection_id NUMBER,
    result_status VARCHAR2(20),
    planned_start_date DATE,
    planned_end_date DATE,
    goal_metric_code VARCHAR2(50),
    goal_target_value NUMBER(18,4),
    goal_actual_value NUMBER(18,4),
    achievement_rate NUMBER(10,6),
    start_risk_stock_qty NUMBER(15,3),
    end_risk_stock_qty NUMBER(15,3),
    start_expected_disposal_qty NUMBER(15,3),
    end_expected_disposal_qty NUMBER(15,3),
    start_unit_cost NUMBER(18,2),
    estimated_loss_savings_amount NUMBER(18,2),
    finalized_sync_run_id NUMBER,
    calculation_version VARCHAR2(50),
    failure_reason VARCHAR2(1000),
    completed_at TIMESTAMP,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    created_by NUMBER,
    updated_by NUMBER,
    is_deleted NUMBER(1) DEFAULT 0
);

CREATE TABLE sales_channel (
    sales_channel_id NUMBER PRIMARY KEY,
    channel_type VARCHAR2(20),
    active_yn CHAR(1),
    is_deleted NUMBER(1)
);

CREATE TABLE sales_point (
    sales_point_id NUMBER PRIMARY KEY,
    sales_channel_id NUMBER,
    sales_point_code VARCHAR2(50),
    sales_point_name VARCHAR2(100),
    active_yn CHAR(1),
    is_deleted NUMBER(1)
);

CREATE TABLE warehouse (
    warehouse_id NUMBER PRIMARY KEY,
    warehouse_code VARCHAR2(50),
    warehouse_name VARCHAR2(100),
    active_yn CHAR(1),
    is_deleted NUMBER(1)
);

CREATE TABLE strategy_action (
    strategy_action_id NUMBER PRIMARY KEY,
    strategy_option_id NUMBER,
    action_type VARCHAR2(30),
    start_date DATE,
    end_date DATE,
    source_sales_point_id NUMBER,
    target_sales_point_id NUMBER,
    source_warehouse_id NUMBER,
    destination_warehouse_id NUMBER,
    is_deleted NUMBER(1)
);

CREATE TABLE strategy_inventory_snapshot (
    inventory_snapshot_id NUMBER PRIMARY KEY,
    strategy_case_id NUMBER,
    sku_id NUMBER,
    lot_id NUMBER,
    sales_point_id NUMBER,
    warehouse_id NUMBER,
    inventory_balance_id NUMBER,
    on_total_qty NUMBER(15,3),
    on_hand_qty NUMBER(15,3),
    forecast_qty NUMBER(15,3),
    expiry_date DATE,
    is_deleted NUMBER(1)
);

CREATE TABLE strategy_simulation (
    simulation_id NUMBER PRIMARY KEY,
    strategy_option_id NUMBER,
    input_source_type VARCHAR2(30),
    expected_sales_qty NUMBER(15,3),
    updated_at TIMESTAMP,
    is_deleted NUMBER(1)
);

CREATE TABLE sku_cost (
    sku_cost_id NUMBER PRIMARY KEY,
    sku_id NUMBER,
    unit_cost NUMBER(18,2),
    effective_from DATE,
    effective_to DATE,
    updated_at TIMESTAMP,
    is_deleted NUMBER(1)
);

CREATE TABLE inventory_sync_run (
    inventory_sync_run_id NUMBER PRIMARY KEY,
    run_status VARCHAR2(30),
    completed_at TIMESTAMP
);

CREATE TABLE lot (
    lot_id NUMBER PRIMARY KEY,
    lot_status VARCHAR2(30),
    expiry_date DATE,
    sale_stop_date DATE,
    is_deleted NUMBER(1)
);

CREATE TABLE inventory_balance (
    inventory_balance_id NUMBER PRIMARY KEY,
    sku_id NUMBER,
    warehouse_id NUMBER,
    stock_sales_point_id NUMBER,
    allocated_sales_point_id NUMBER,
    lot_id NUMBER,
    on_hand_qty NUMBER(15,3),
    total_qty NUMBER(15,3),
    is_deleted NUMBER(1)
);

CREATE TABLE risk_assessment (
    risk_assessment_id NUMBER PRIMARY KEY,
    inventory_balance_id NUMBER,
    forecast_id NUMBER,
    risk_grade VARCHAR2(20),
    updated_at TIMESTAMP,
    is_deleted NUMBER(1)
);

CREATE TABLE demand_forecast (
    forecast_id NUMBER PRIMARY KEY,
    predicted_qty_d7 NUMBER(15,3),
    predicted_qty_d14 NUMBER(15,3),
    predicted_qty_d30 NUMBER(15,3),
    predicted_qty_d60 NUMBER(15,3),
    predicted_qty_d90 NUMBER(15,3),
    is_deleted NUMBER(1)
);

CREATE TABLE sales_daily (
    sales_daily_id NUMBER PRIMARY KEY,
    sku_id NUMBER,
    sales_point_id NUMBER,
    sales_date DATE,
    net_sales_qty NUMBER(15,3),
    is_deleted NUMBER(1)
);

INSERT INTO strategy_case VALUES (101, 10001, 'EXECUTING', 0);
INSERT INTO strategy_option VALUES (1001, 101, 0);
INSERT INTO final_strategy_selection VALUES (5001, 101, 1001, 1, 0);
INSERT INTO strategy_execution_result (
    strategy_execution_result_id, final_selection_id, result_status,
    planned_start_date, planned_end_date, achievement_rate,
    start_risk_stock_qty, end_risk_stock_qty,
    start_expected_disposal_qty, end_expected_disposal_qty,
    estimated_loss_savings_amount, is_deleted
) VALUES (
    9001, 5001, 'COMPLETED', DATE '2026-08-01', DATE '2026-08-10', 120,
    100, 40, 30, 10, 2000, 0
);

INSERT INTO sales_channel VALUES (1, 'OFFLINE', 'Y', 0);
INSERT INTO sales_point VALUES (10, 1, 'STORE-1', '매장 1', 'Y', 0);
INSERT INTO warehouse VALUES (20, 'WH-1', '물류센터 1', 'Y', 0);

INSERT INTO strategy_action VALUES (
    1, 1001, 'REALLOCATION', DATE '2026-08-01', DATE '2026-08-10',
    NULL, 10, 20, NULL, 0
);
INSERT INTO strategy_action VALUES (
    2, 1001, 'PRICE_DISCOUNT', DATE '2026-08-01', DATE '2026-08-10',
    NULL, 10, NULL, NULL, 0
);
INSERT INTO strategy_inventory_snapshot VALUES (
    1, 101, 10001, 20001, NULL, 20, 30001, 100, 90, 20, DATE '2026-08-10', 0
);

INSERT INTO strategy_case VALUES (102, 10002, 'READY_TO_EXECUTE', 0);
INSERT INTO strategy_option VALUES (1002, 102, 0);
INSERT INTO final_strategy_selection VALUES (5002, 102, 1002, 7, 0);
INSERT INTO strategy_action VALUES (
    3, 1002, 'PRICE_DISCOUNT', DATE '2026-08-15', DATE '2026-08-22',
    NULL, 10, NULL, NULL, 0
);
INSERT INTO strategy_simulation VALUES (
    1, 1002, 'USER_SELECT', 80, TIMESTAMP '2026-08-14 10:00:00', 0
);
INSERT INTO sku_cost VALUES (
    1, 10002, 2500, DATE '2026-08-01', NULL, TIMESTAMP '2026-08-01 00:00:00', 0
);
INSERT INTO strategy_inventory_snapshot VALUES (
    2, 102, 10002, 20002, 10, NULL, 30002, 100, 90, 50, DATE '2026-08-20', 0
);

INSERT INTO strategy_case VALUES (103, 10003, 'EXECUTING', 0);
INSERT INTO strategy_option VALUES (1003, 103, 0);
INSERT INTO final_strategy_selection VALUES (5003, 103, 1003, 9, 0);
INSERT INTO strategy_action VALUES (
    4, 1003, 'PRICE_DISCOUNT', DATE '2026-08-01', DATE '2026-08-10',
    NULL, 10, NULL, NULL, 0
);
INSERT INTO strategy_inventory_snapshot VALUES (
    3, 103, 10003, 20003, 10, NULL, 30003, 100, 90, 60, DATE '2026-08-15', 0
);
INSERT INTO strategy_execution_result (
    final_selection_id, result_status, planned_start_date, planned_end_date,
    goal_metric_code, goal_target_value, start_risk_stock_qty,
    start_expected_disposal_qty, start_unit_cost, calculation_version,
    created_by, updated_by
) VALUES (
    5003, 'RUNNING', DATE '2026-08-01', DATE '2026-08-10',
    'SALES_QTY', 80, 100, 30, 1000, 'SALES_ONLY_V1', 9, 9
);
INSERT INTO inventory_sync_run VALUES (7001, 'SUCCEEDED', TIMESTAMP '2026-08-11 00:45:00');
INSERT INTO lot VALUES (20003, 'AVAILABLE', DATE '2026-08-20', DATE '2026-08-15', 0);
INSERT INTO inventory_balance VALUES (30003, 10003, NULL, 10, 10, 20003, 40, 40, 0);
INSERT INTO demand_forecast VALUES (8001, 10, 20, 30, 40, 50, 0);
INSERT INTO risk_assessment VALUES (
    90001, 30003, 8001, 'WARNING', TIMESTAMP '2026-08-11 00:40:00', 0
);
INSERT INTO sales_daily VALUES (91001, 10003, 10, DATE '2026-08-05', 50, 0);
