package com.stockit.backend.common.persistence;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class StrategyPerformanceSyncMigrationContractTest {
    private static final String MIGRATION_PATH =
            "db/migration/V31__support_strategy_performance_sync.sql";

    @Test
    void createsDailyUniquenessAndSingletonMutex(@TempDir Path tempDir) throws Exception {
        Path migrationFile = tempDir.resolve("V31__support_strategy_performance_sync.sql");
        try (InputStream input = requiredResource()) {
            String migration = new String(input.readAllBytes(), StandardCharsets.UTF_8);
            int oracleBlockEnd = migration.indexOf("\n/\n");
            assertThat(oracleBlockEnd).isNotNegative();
            // H2 cannot parse Oracle anonymous PL/SQL; its contract is asserted below.
            Files.writeString(migrationFile, migration.substring(oracleBlockEnd + 3));
        }

        String jdbcUrl = "jdbc:h2:mem:strategy-performance-sync-migration;MODE=Oracle;DB_CLOSE_DELAY=-1";
        try (Connection connection = DriverManager.getConnection(jdbcUrl, "sa", "");
             Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE strategy_performance (
                        strategy_performance_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        strategy_option_id NUMBER NOT NULL,
                        performance_date DATE NOT NULL
                    )
                    """);
        }

        Flyway.configure()
                .dataSource(jdbcUrl, "sa", "")
                .locations("filesystem:" + tempDir.toAbsolutePath())
                .baselineOnMigrate(true)
                .baselineVersion("30")
                .load()
                .migrate();

        try (Connection connection = DriverManager.getConnection(jdbcUrl, "sa", "");
             Statement statement = connection.createStatement()) {
            statement.execute("INSERT INTO strategy_performance (strategy_option_id, performance_date) VALUES (10, DATE '2026-08-26')");
            assertThatThrownBy(() -> statement.execute(
                    "INSERT INTO strategy_performance (strategy_option_id, performance_date) VALUES (10, DATE '2026-08-26')"
            )).isInstanceOf(Exception.class);

            try (ResultSet result = statement.executeQuery("SELECT mutex_id FROM strategy_perf_sync_mutex")) {
                assertThat(result.next()).isTrue();
                assertThat(result.getInt(1)).isEqualTo(1);
                assertThat(result.next()).isFalse();
            }
        }
    }

    @Test
    void documentsThePerformanceSynchronizationContract() throws Exception {
        String migration;
        try (InputStream input = requiredResource()) {
            migration = new String(input.readAllBytes(), StandardCharsets.UTF_8);
        }

        assertThat(migration).contains(
                "HAVING COUNT(*) > 1",
                "RAISE_APPLICATION_ERROR(",
                "V31 blocked: duplicate strategy_performance option/date groups exist",
                "UNIQUE (strategy_option_id, performance_date)",
                "CREATE TABLE strategy_perf_sync_mutex",
                "CHECK (mutex_id = 1)",
                "INSERT INTO strategy_perf_sync_mutex (mutex_id) VALUES (1)"
        );
    }

    private static InputStream requiredResource() {
        InputStream input = StrategyPerformanceSyncMigrationContractTest.class
                .getClassLoader()
                .getResourceAsStream(MIGRATION_PATH);
        if (input == null) {
            throw new IllegalStateException("Missing migration: " + MIGRATION_PATH);
        }
        return input;
    }
}
