global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: stockit-backend
    scheme: https
    metrics_path: /actuator/prometheus
    tls_config:
      server_name: api.stockfit.win
    static_configs:
      - targets:
          - 10.0.10.150:443
        labels:
          environment: production

  - job_name: stockit-node
    static_configs:
      - targets:
          - 10.0.10.150:9100
        labels:
          environment: production
