DROP TABLE IF EXISTS user_role;
DROP TABLE IF EXISTS app_role;
DROP TABLE IF EXISTS app_user;
DROP TABLE IF EXISTS organization;

CREATE TABLE organization (
    organization_id NUMBER PRIMARY KEY,
    organization_name VARCHAR2(200) NOT NULL,
    is_deleted NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE app_user (
    user_id NUMBER PRIMARY KEY,
    organization_id NUMBER NOT NULL,
    login_id VARCHAR2(100) NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    user_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(255),
    active_yn CHAR(1) DEFAULT 'Y' NOT NULL,
    last_login_at TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by NUMBER NOT NULL,
    is_deleted NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE app_role (
    role_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code VARCHAR2(50) NOT NULL,
    role_name VARCHAR2(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by NUMBER NOT NULL,
    updated_by NUMBER NOT NULL,
    CONSTRAINT uq_app_role_code UNIQUE (role_code),
    is_deleted NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE user_role (
    user_role_id NUMBER PRIMARY KEY,
    user_id NUMBER NOT NULL,
    role_id NUMBER NOT NULL,
    CONSTRAINT uq_user_role UNIQUE (user_id, role_id),
    is_deleted NUMBER(1) DEFAULT 0 NOT NULL
);

INSERT INTO organization (
    organization_id,
    organization_name,
    is_deleted
) VALUES (
    100,
    'SYSTEM',
    0
);

INSERT INTO app_user (
    user_id,
    organization_id,
    login_id,
    password_hash,
    user_name,
    active_yn,
    updated_by,
    is_deleted
) VALUES (
    100,
    100,
    '__system__',
    '$2a$12$000000000000000000000uG1HiS9B56XZQ7W3sXa6iRDAe9PS6NuW',
    'SYSTEM',
    'N',
    100,
    0
);
