DROP TABLE IF EXISTS demand_forecast;
DROP TABLE IF EXISTS ml_model_version;
DROP TABLE IF EXISTS sku;
DROP TABLE IF EXISTS sales_point;

CREATE TABLE ml_model_version (
    model_version_id NUMBER PRIMARY KEY,
    model_name VARCHAR2(100) NOT NULL,
    model_version VARCHAR2(50) NOT NULL,
    is_deleted NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT uq_test_model_version UNIQUE (model_name, model_version)
);

CREATE TABLE sku (
    sku_id NUMBER PRIMARY KEY,
    is_deleted NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE sales_point (
    sales_point_id NUMBER PRIMARY KEY,
    is_deleted NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE demand_forecast (
    forecast_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku_id NUMBER NOT NULL,
    sales_point_id NUMBER NOT NULL,
    model_version_id NUMBER NOT NULL,
    base_date DATE NOT NULL,
    predicted_qty_d7 NUMBER(15,3) NOT NULL,
    predicted_qty_d14 NUMBER(15,3) NOT NULL,
    predicted_qty_d30 NUMBER(15,3) NOT NULL,
    predicted_qty_d60 NUMBER(15,3) NOT NULL,
    predicted_qty_d90 NUMBER(15,3) NOT NULL,
    forecast_source VARCHAR2(40) NOT NULL,
    confidence_level VARCHAR2(10) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by NUMBER NOT NULL,
    updated_by NUMBER NOT NULL,
    is_deleted NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT uq_test_forecast_target UNIQUE (
        sku_id, sales_point_id, model_version_id, base_date
    )
);

INSERT INTO ml_model_version (
    model_version_id, model_name, model_version, is_deleted
) VALUES (7, 'stockit-demand-lightgbm', '1', 0);

INSERT INTO sku (sku_id, is_deleted) VALUES (101, 0);
INSERT INTO sku (sku_id, is_deleted) VALUES (102, 0);
INSERT INTO sales_point (sales_point_id, is_deleted) VALUES (10, 0);
