DROP TABLE IF EXISTS demand_forecast;
DROP TABLE IF EXISTS demand_forecast_staging;
DROP TABLE IF EXISTS demand_forecast_import_batch;
DROP TABLE IF EXISTS demand_forecast_run;
DROP TABLE IF EXISTS ml_model_version;
DROP TABLE IF EXISTS sku;
DROP TABLE IF EXISTS sales_point;
DROP TABLE IF EXISTS app_user;

CREATE TABLE app_user (
    user_id NUMBER PRIMARY KEY
);

CREATE TABLE ml_model_version (
    model_version_id NUMBER PRIMARY KEY,
    model_name VARCHAR2(100) NOT NULL,
    model_version VARCHAR2(50) NOT NULL,
    is_deleted NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT uq_test_model_version UNIQUE (model_name, model_version)
);

CREATE TABLE sku (
    sku_id NUMBER PRIMARY KEY,
    is_deleted NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE sales_point (
    sales_point_id NUMBER PRIMARY KEY,
    is_deleted NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE demand_forecast_run (
    forecast_run_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_request_id VARCHAR2(80) NOT NULL UNIQUE,
    trigger_type VARCHAR2(20) NOT NULL,
    base_date DATE NOT NULL,
    model_version_id NUMBER,
    azure_job_id VARCHAR2(255) UNIQUE,
    run_status VARCHAR2(30) NOT NULL,
    current_stage VARCHAR2(30),
    total_batches NUMBER(10),
    total_items NUMBER(19),
    received_batches NUMBER(10) DEFAULT 0 NOT NULL,
    received_items NUMBER(19) DEFAULT 0 NOT NULL,
    import_requested_at TIMESTAMP,
    all_batches_received_at TIMESTAMP,
    started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by NUMBER NOT NULL,
    updated_by NUMBER NOT NULL,
    is_deleted NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE demand_forecast_import_batch (
    forecast_import_batch_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    forecast_run_id NUMBER NOT NULL,
    batch_number NUMBER(10) NOT NULL,
    item_count NUMBER(10) NOT NULL,
    payload_hash CHAR(64) NOT NULL,
    received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by NUMBER NOT NULL,
    CONSTRAINT uq_test_import_batch UNIQUE (forecast_run_id, batch_number)
);

CREATE TABLE demand_forecast_staging (
    forecast_staging_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    forecast_run_id NUMBER NOT NULL,
    batch_number NUMBER(10) NOT NULL,
    sku_id NUMBER NOT NULL,
    sales_point_id NUMBER NOT NULL,
    predicted_qty_d7 NUMBER(15,3) NOT NULL,
    predicted_qty_d14 NUMBER(15,3) NOT NULL,
    predicted_qty_d30 NUMBER(15,3) NOT NULL,
    predicted_qty_d60 NUMBER(15,3) NOT NULL,
    predicted_qty_d90 NUMBER(15,3) NOT NULL,
    forecast_source VARCHAR2(40) NOT NULL,
    confidence_level VARCHAR2(10) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by NUMBER NOT NULL,
    CONSTRAINT uq_test_staging_target UNIQUE (forecast_run_id, sku_id, sales_point_id)
);

CREATE TABLE demand_forecast (
    forecast_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku_id NUMBER NOT NULL,
    sales_point_id NUMBER NOT NULL,
    model_version_id NUMBER NOT NULL,
    base_date DATE NOT NULL,
    predicted_qty_d7 NUMBER(15,3) NOT NULL,
    predicted_qty_d14 NUMBER(15,3) NOT NULL,
    predicted_qty_d30 NUMBER(15,3) NOT NULL,
    predicted_qty_d60 NUMBER(15,3) NOT NULL,
    predicted_qty_d90 NUMBER(15,3) NOT NULL,
    forecast_source VARCHAR2(40) NOT NULL,
    confidence_level VARCHAR2(10) NOT NULL,
    forecast_run_id NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by NUMBER NOT NULL,
    updated_by NUMBER NOT NULL,
    is_deleted NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT uq_test_forecast_target UNIQUE (
        sku_id, sales_point_id, model_version_id, base_date
    )
);

INSERT INTO ml_model_version (
    model_version_id, model_name, model_version, is_deleted
) VALUES (7, 'stockit-demand-lightgbm', '1', 0);

INSERT INTO app_user (user_id) VALUES (99);
INSERT INTO sku (sku_id, is_deleted) VALUES (101, 0);
INSERT INTO sku (sku_id, is_deleted) VALUES (102, 0);
INSERT INTO sales_point (sales_point_id, is_deleted) VALUES (10, 0);
