DROP TABLE IF EXISTS sales_daily;

CREATE TABLE sales_daily (
    sales_daily_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku_id NUMBER NOT NULL,
    sales_point_id NUMBER NOT NULL,
    sales_date DATE NOT NULL,
    net_sales_qty NUMBER(15, 3),
    is_deleted NUMBER(1) DEFAULT 0 NOT NULL
);
