DROP TABLE IF EXISTS strategy_case;
DROP TABLE IF EXISTS inventory_balance;
DROP TABLE IF EXISTS lot;
DROP TABLE IF EXISTS sales_point;
DROP TABLE IF EXISTS sku;

CREATE TABLE sku (
    sku_id NUMBER PRIMARY KEY,
    sku_name VARCHAR2(200) NOT NULL,
    active_yn CHAR(1) NOT NULL,
    is_deleted NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE sales_point (
    sales_point_id NUMBER PRIMARY KEY,
    active_yn CHAR(1) NOT NULL,
    is_deleted NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE lot (
    lot_id NUMBER PRIMARY KEY,
    sku_id NUMBER NOT NULL,
    lot_status VARCHAR2(30) NOT NULL,
    is_deleted NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE inventory_balance (
    inventory_balance_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku_id NUMBER NOT NULL,
    lot_id NUMBER,
    warehouse_id NUMBER,
    stock_sales_point_id NUMBER,
    allocated_sales_point_id NUMBER,
    on_hand_qty NUMBER(15,3) DEFAULT 0 NOT NULL,
    is_deleted NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE strategy_case (
    strategy_case_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku_id NUMBER NOT NULL,
    created_by NUMBER NOT NULL,
    requested_sales_point_id NUMBER,
    case_code VARCHAR2(50) NOT NULL UNIQUE,
    case_status VARCHAR2(30) NOT NULL,
    generation_stage VARCHAR2(30),
    recommendation_outcome VARCHAR2(30),
    case_name VARCHAR2(200) NOT NULL,
    request_payload_json CLOB NOT NULL,
    result_cache_key VARCHAR2(500),
    result_expires_at TIMESTAMP,
    failure_code VARCHAR2(100),
    failure_message VARCHAR2(2000),
    completed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by NUMBER NOT NULL,
    is_deleted NUMBER(1) DEFAULT 0 NOT NULL
);

INSERT INTO sku (sku_id, sku_name, active_yn, is_deleted)
VALUES (101, '테스트 SKU', 'Y', 0);
INSERT INTO sku (sku_id, sku_name, active_yn, is_deleted)
VALUES (102, '비활성 SKU', 'N', 0);

INSERT INTO sales_point (sales_point_id, active_yn, is_deleted) VALUES (10, 'Y', 0);
INSERT INTO sales_point (sales_point_id, active_yn, is_deleted) VALUES (20, 'Y', 0);
INSERT INTO sales_point (sales_point_id, active_yn, is_deleted) VALUES (30, 'N', 0);

INSERT INTO lot (lot_id, sku_id, lot_status, is_deleted)
VALUES (1001, 101, 'AVAILABLE', 0);
INSERT INTO lot (lot_id, sku_id, lot_status, is_deleted)
VALUES (1002, 101, 'EXPIRED', 0);
INSERT INTO lot (lot_id, sku_id, lot_status, is_deleted)
VALUES (1003, 102, 'AVAILABLE', 0);
INSERT INTO inventory_balance (
    sku_id, lot_id, warehouse_id, stock_sales_point_id, on_hand_qty, is_deleted
) VALUES (101, 1001, 501, 10, 5, 0);
INSERT INTO inventory_balance (
    sku_id, warehouse_id, allocated_sales_point_id, on_hand_qty, is_deleted
) VALUES (101, 501, 20, 3, 0);
INSERT INTO inventory_balance (
    sku_id, warehouse_id, stock_sales_point_id, on_hand_qty, is_deleted
) VALUES (101, 501, 30, 7, 0);
INSERT INTO inventory_balance (
    sku_id, warehouse_id, stock_sales_point_id, on_hand_qty, is_deleted
) VALUES (102, 501, 10, 0, 0);
