DROP ALL OBJECTS;

CREATE TABLE product (
    product_id NUMBER PRIMARY KEY, product_name VARCHAR2(200), image_url VARCHAR2(1000), is_deleted NUMBER(1)
);
CREATE TABLE sku (
    sku_id NUMBER PRIMARY KEY, product_id NUMBER, sku_code VARCHAR2(50), sku_name VARCHAR2(200),
    unit_code VARCHAR2(20), is_deleted NUMBER(1)
);
CREATE TABLE strategy_case (
    strategy_case_id NUMBER PRIMARY KEY, sku_id NUMBER, case_code VARCHAR2(50), case_name VARCHAR2(200),
    case_status VARCHAR2(30), is_deleted NUMBER(1)
);
CREATE TABLE strategy_option (
    strategy_option_id NUMBER PRIMARY KEY, strategy_case_id NUMBER, option_name VARCHAR2(200),
    recommendation_reason VARCHAR2(2000), is_deleted NUMBER(1)
);
CREATE TABLE final_strategy_selection (
    final_selection_id NUMBER PRIMARY KEY, strategy_case_id NUMBER, strategy_option_id NUMBER,
    created_at TIMESTAMP, last_synced_at TIMESTAMP, updated_at TIMESTAMP, updated_by NUMBER,
    is_deleted NUMBER(1)
);
CREATE TABLE sales_point (
    sales_point_id NUMBER PRIMARY KEY, sales_point_code VARCHAR2(50), sales_point_name VARCHAR2(200),
    is_deleted NUMBER(1)
);
CREATE TABLE warehouse (
    warehouse_id NUMBER PRIMARY KEY, warehouse_code VARCHAR2(50), warehouse_name VARCHAR2(200),
    is_deleted NUMBER(1)
);
CREATE TABLE strategy_action (
    strategy_action_id NUMBER PRIMARY KEY, strategy_option_id NUMBER, action_type VARCHAR2(30),
    action_quantity NUMBER(15,3), action_order NUMBER(5), start_date DATE, end_date DATE,
    source_sales_point_id NUMBER, target_sales_point_id NUMBER, source_warehouse_id NUMBER,
    destination_warehouse_id NUMBER, is_deleted NUMBER(1)
);
CREATE TABLE inventory_balance (
    inventory_balance_id NUMBER PRIMARY KEY, sku_id NUMBER, warehouse_id NUMBER,
    stock_sales_point_id NUMBER, allocated_sales_point_id NUMBER,
    on_hand_qty NUMBER(15,3), is_deleted NUMBER(1)
);
CREATE TABLE strategy_inventory_snapshot (
    inventory_snapshot_id NUMBER PRIMARY KEY, strategy_case_id NUMBER, sales_point_id NUMBER,
    warehouse_id NUMBER, inventory_balance_id NUMBER, on_hand_qty NUMBER(15,3),
    safety_stock_qty NUMBER(15,3), is_deleted NUMBER(1)
);
CREATE TABLE sales_daily (
    sales_daily_id NUMBER PRIMARY KEY, sku_id NUMBER, sales_point_id NUMBER, sales_date DATE,
    net_sales_qty NUMBER(15,3), net_sales_amount NUMBER(18,2), is_deleted NUMBER(1)
);
CREATE TABLE sku_channel_price (
    sku_channel_price_id NUMBER PRIMARY KEY, sku_id NUMBER, sales_point_id NUMBER,
    product_cost NUMBER(18,2), payment_fee NUMBER(18,2), logistics_cost NUMBER(18,2),
    effective_from DATE, effective_to DATE, updated_at TIMESTAMP, is_deleted NUMBER(1)
);
CREATE TABLE strategy_performance (
    strategy_performance_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_option_id NUMBER, performance_date DATE,
    actual_sales_qty NUMBER(15,3), actual_revenue NUMBER(18,2), actual_contribution_margin NUMBER(18,2),
    actual_remaining_qty NUMBER(15,3), moved_quantity NUMBER(15,3), disposed_quantity NUMBER(15,3),
    created_at TIMESTAMP, updated_at TIMESTAMP, created_by NUMBER, updated_by NUMBER,
    is_deleted NUMBER(1),
    CONSTRAINT uq_strategy_perf_option_date UNIQUE (strategy_option_id, performance_date)
);
CREATE TABLE strategy_perf_sync_mutex (mutex_id NUMBER(1) PRIMARY KEY);
CREATE TABLE strategy_execution_result (
    strategy_execution_result_id NUMBER PRIMARY KEY, final_selection_id NUMBER,
    result_status VARCHAR2(20), planned_start_date DATE, planned_end_date DATE,
    goal_target_value NUMBER(18,4), goal_actual_value NUMBER(18,4),
    achievement_rate NUMBER(10,6), is_deleted NUMBER(1)
);

INSERT INTO product VALUES (1, '테스트 상품', 'https://example.com/image.jpg', 0);
INSERT INTO product VALUES (2, '국산콩 두부', NULL, 0);
INSERT INTO product VALUES (3, '왕교자 만두', NULL, 0);
INSERT INTO sku VALUES (1, 1, 'SKU-1', '테스트 SKU', '개', 0);
INSERT INTO sku VALUES (2, 2, 'SKU-2', '두부 SKU', '개', 0);
INSERT INTO sku VALUES (3, 3, 'SKU-3', '만두 SKU', '개', 0);
INSERT INTO strategy_case VALUES (101, 1, 'SC-101', '테스트 전략', 'EXECUTING', 0);
INSERT INTO strategy_case VALUES (102, 2, 'SC-102', '두부 전략', 'READY_TO_EXECUTE', 0);
INSERT INTO strategy_case VALUES (103, 3, 'SC-103', '만두 전략', 'EXECUTION_COMPLETED', 0);
INSERT INTO strategy_option VALUES (1000, 101, '이전 선택 전략', '이전 선택', 0);
INSERT INTO strategy_option VALUES (1001, 101, '재할당 전략', '재고 편중 완화', 0);
INSERT INTO strategy_option VALUES (1002, 102, '할인 전략', '회전율 개선', 0);
INSERT INTO strategy_option VALUES (1003, 103, '채널 전략', '판매처 확대', 0);
INSERT INTO final_strategy_selection VALUES (
    5000, 101, 1000, TIMESTAMP '2026-04-01 10:00:00', NULL, NULL, NULL, 0
);
INSERT INTO final_strategy_selection VALUES (
    5001, 101, 1001, TIMESTAMP '2026-05-01 10:00:00', TIMESTAMP '2026-05-03 12:00:00', NULL, NULL, 0
);
INSERT INTO final_strategy_selection VALUES (
    5002, 102, 1002, TIMESTAMP '2026-05-01 10:00:00', NULL, NULL, NULL, 0
);
INSERT INTO final_strategy_selection VALUES (
    5003, 103, 1003, TIMESTAMP '2026-04-30 10:00:00', NULL, NULL, NULL, 0
);
INSERT INTO strategy_execution_result VALUES (
    9000, 5001, 'PARTIAL', DATE '2026-05-01', DATE '2026-05-10', 12, NULL, NULL, 0
);
INSERT INTO strategy_execution_result VALUES (
    9001, 5001, 'COMPLETED', DATE '2026-05-01', DATE '2026-05-10', 12, 12, 100, 0
);
INSERT INTO strategy_execution_result VALUES (
    9002, 5002, 'PARTIAL', DATE '2026-05-01', DATE '2026-05-10', 10, NULL, NULL, 0
);
INSERT INTO sales_point VALUES (10, 'GREETING', '그리팅몰', 0);
INSERT INTO warehouse VALUES (501, 'SEONGNAM', '성남센터', 0);
INSERT INTO warehouse VALUES (502, 'GYEONGIN1', '경인1센터', 0);
INSERT INTO strategy_action VALUES (
    11, 1001, 'REALLOCATION', 20, 1, DATE '2026-05-01', DATE '2026-05-10',
    NULL, 10, 501, 502, 0
);
INSERT INTO strategy_action VALUES (
    12, 1001, 'PRICE_DISCOUNT', 10, 2, DATE '2026-05-01', DATE '2026-05-10',
    NULL, 10, NULL, NULL, 0
);
INSERT INTO strategy_action VALUES (
    21, 1002, 'PRICE_DISCOUNT', 10, 1, DATE '2026-05-01', DATE '2026-05-10',
    NULL, 10, NULL, NULL, 0
);
INSERT INTO strategy_action VALUES (
    31, 1003, 'CHANNEL_EXPANSION', 10, 1, DATE '2026-05-01', DATE '2026-05-10',
    NULL, 10, NULL, NULL, 0
);
INSERT INTO inventory_balance VALUES (9001, 1, 501, NULL, NULL, 80, 0);
INSERT INTO strategy_inventory_snapshot VALUES (8001, 101, NULL, 501, 9001, 100, 30, 0);
INSERT INTO sales_daily VALUES (7001, 1, 10, DATE '2026-05-02', 7, 70000, 0);
INSERT INTO sales_daily VALUES (7004, 1, 10, DATE '2026-07-28', 4, 40000, 0);
INSERT INTO sales_daily VALUES (7002, 1, 10, DATE '2026-07-29', 3, 30000, 0);
INSERT INTO sales_daily VALUES (7003, 1, 10, DATE '2026-07-30', 99, 990000, 0);
INSERT INTO sku_channel_price VALUES (
    3001, 1, 10, 5000, 500, 500, DATE '2026-01-01', NULL, TIMESTAMP '2026-01-01 00:00:00', 0
);
INSERT INTO strategy_performance (
    strategy_performance_id, strategy_option_id, performance_date, actual_sales_qty,
    actual_revenue, actual_contribution_margin, actual_remaining_qty, moved_quantity,
    disposed_quantity, is_deleted
) VALUES (6001, 1001, DATE '2026-05-02', 7, 70000, 30000, 93, 10, 0, 0);
INSERT INTO strategy_performance (
    strategy_performance_id, strategy_option_id, performance_date, actual_sales_qty,
    actual_revenue, actual_contribution_margin, actual_remaining_qty, moved_quantity,
    disposed_quantity, is_deleted
) VALUES (6002, 1001, DATE '2026-05-03', 5, 50000, 20000, 88, 10, 0, 0);
INSERT INTO strategy_perf_sync_mutex VALUES (1);
