CREATE TABLE strategy_forecast_snapshot (
    strategy_forecast_snapshot_id NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,

    final_selection_id            NUMBER        NOT NULL,
    sales_point_id                NUMBER        NOT NULL,
    model_version_id              NUMBER        NOT NULL,

    forecast_role                 VARCHAR2(20)  NOT NULL,
    forecast_run_id               VARCHAR2(200) NOT NULL,

    strategy_period_predicted_qty NUMBER(15,3)  NOT NULL,
    forecast_30d_qty              NUMBER(15,3),
    forecast_60d_qty              NUMBER(15,3),
    forecast_90d_qty              NUMBER(15,3),
    forecast_180d_qty             NUMBER(15,3),

    daily_forecast_json           CLOB          NOT NULL,
    input_data_hash               VARCHAR2(64)  NOT NULL,
    forecast_generated_at         TIMESTAMP     NOT NULL,

    created_at                    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at                    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    created_by                    NUMBER        NOT NULL,
    updated_by                    NUMBER        NOT NULL,
    is_deleted                    NUMBER(1) DEFAULT 0 NOT NULL,

    CONSTRAINT pk_strategy_forecast_snapshot
        PRIMARY KEY (strategy_forecast_snapshot_id),

    CONSTRAINT uq_strat_fcst_final_point
        UNIQUE (
            final_selection_id,
            sales_point_id,
            forecast_role
        ),

    CONSTRAINT fk_strat_fcst_final
        FOREIGN KEY (final_selection_id)
            REFERENCES final_strategy_selection (final_selection_id),

    CONSTRAINT fk_strat_fcst_point
        FOREIGN KEY (sales_point_id)
            REFERENCES sales_point (sales_point_id),

    CONSTRAINT fk_strat_fcst_model
        FOREIGN KEY (model_version_id)
            REFERENCES ml_model_version (model_version_id),

    CONSTRAINT fk_strat_fcst_created_by
        FOREIGN KEY (created_by)
            REFERENCES app_user (user_id),

    CONSTRAINT fk_strat_fcst_updated_by
        FOREIGN KEY (updated_by)
            REFERENCES app_user (user_id),

    CONSTRAINT ck_strat_fcst_role
        CHECK (
            forecast_role IN ('SOURCE', 'TARGET')
        ),

    CONSTRAINT ck_strat_fcst_qty_nonnegative
        CHECK (
            strategy_period_predicted_qty >= 0
            AND (forecast_30d_qty IS NULL OR forecast_30d_qty >= 0)
            AND (forecast_60d_qty IS NULL OR forecast_60d_qty >= 0)
            AND (forecast_90d_qty IS NULL OR forecast_90d_qty >= 0)
            AND (forecast_180d_qty IS NULL OR forecast_180d_qty >= 0)
        ),

    CONSTRAINT ck_strat_fcst_qty_cumulative
        CHECK (
            (
                forecast_30d_qty IS NULL
                OR forecast_60d_qty IS NULL
                OR forecast_30d_qty <= forecast_60d_qty
            )
            AND (
                forecast_60d_qty IS NULL
                OR forecast_90d_qty IS NULL
                OR forecast_60d_qty <= forecast_90d_qty
            )
            AND (
                forecast_90d_qty IS NULL
                OR forecast_180d_qty IS NULL
                OR forecast_90d_qty <= forecast_180d_qty
            )
        ),

    CONSTRAINT ck_strat_fcst_json
        CHECK (daily_forecast_json IS JSON),

    CONSTRAINT ck_strat_fcst_deleted
        CHECK (is_deleted IN (0, 1))
);

CREATE INDEX ix_strat_fcst_sales_point
    ON strategy_forecast_snapshot (sales_point_id);

COMMENT ON TABLE strategy_forecast_snapshot
    IS '최종 선택 전략에 사용된 판매처별 수요예측 스냅샷';

COMMENT ON COLUMN
    strategy_forecast_snapshot.strategy_forecast_snapshot_id
    IS '전략 수요예측 스냅샷 ID';

COMMENT ON COLUMN
    strategy_forecast_snapshot.final_selection_id
    IS '최종 전략 선택 ID';

COMMENT ON COLUMN
    strategy_forecast_snapshot.sales_point_id
    IS '수요예측 대상 판매처 ID';

COMMENT ON COLUMN
    strategy_forecast_snapshot.model_version_id
    IS '수요예측에 사용한 ML 모델 버전 ID';

COMMENT ON COLUMN
    strategy_forecast_snapshot.forecast_role
    IS '판매처 역할: SOURCE 또는 TARGET';

COMMENT ON COLUMN
    strategy_forecast_snapshot.forecast_run_id
    IS '요청 시 실행된 수요예측 작업 식별자';

COMMENT ON COLUMN
    strategy_forecast_snapshot.strategy_period_predicted_qty
    IS '최종 전략 적용 기간의 예측 수요량 합계';

COMMENT ON COLUMN
    strategy_forecast_snapshot.forecast_30d_qty
    IS '예측 생성일부터 30일간의 누적 예측 수요량';

COMMENT ON COLUMN
    strategy_forecast_snapshot.forecast_60d_qty
    IS '예측 생성일부터 60일간의 누적 예측 수요량';

COMMENT ON COLUMN
    strategy_forecast_snapshot.forecast_90d_qty
    IS '예측 생성일부터 90일간의 누적 예측 수요량';

COMMENT ON COLUMN
    strategy_forecast_snapshot.forecast_180d_qty
    IS '예측 생성일부터 180일간의 누적 예측 수요량';

COMMENT ON COLUMN
    strategy_forecast_snapshot.daily_forecast_json
    IS '최종 전략 적용 기간의 일별 수요예측 JSON';

COMMENT ON COLUMN
    strategy_forecast_snapshot.input_data_hash
    IS '수요예측 입력 데이터 식별 해시';

COMMENT ON COLUMN
    strategy_forecast_snapshot.forecast_generated_at
    IS '수요예측 생성일시';

COMMENT ON COLUMN
    strategy_forecast_snapshot.created_at
    IS '생성일시';

COMMENT ON COLUMN
    strategy_forecast_snapshot.updated_at
    IS '수정일시';

COMMENT ON COLUMN
    strategy_forecast_snapshot.created_by
    IS '생성자 ID';

COMMENT ON COLUMN
    strategy_forecast_snapshot.updated_by
    IS '수정자 ID';

COMMENT ON COLUMN
    strategy_forecast_snapshot.is_deleted
    IS '삭제 여부: 0 활성, 1 삭제';
