CREATE TABLE organization (
                              organization_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY        NOT NULL,
                              organization_code VARCHAR2(50)  NOT NULL,
                              organization_name VARCHAR2(200) NOT NULL,
                              organization_type VARCHAR2(30)  NOT NULL,
                              CONSTRAINT pk_organization PRIMARY KEY (organization_id),
                              CONSTRAINT uq_organization_code UNIQUE (organization_code),
                              CONSTRAINT ck_org_type CHECK (
                                  organization_type IN ('HEAD_OFFICE', 'ONLINE_CHANNEL', 'OFFLINE_STORE', 'WAREHOUSE')
                                  )
);

CREATE TABLE sales_channel (
                               sales_channel_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY        NOT NULL,
                               channel_code     VARCHAR2(50)  NOT NULL,
                               channel_name     VARCHAR2(100) NOT NULL,
                               channel_type     VARCHAR2(20)  NOT NULL,
                               active_yn        CHAR(1) DEFAULT 'Y' NOT NULL,
                               CONSTRAINT pk_sales_channel PRIMARY KEY (sales_channel_id),
                               CONSTRAINT uq_sales_channel_code UNIQUE (channel_code),
                               CONSTRAINT ck_sales_channel_type CHECK (channel_type IN ('ONLINE', 'OFFLINE')),
                               CONSTRAINT ck_sales_channel_active CHECK (active_yn IN ('Y', 'N'))
);

CREATE TABLE warehouse (
                           warehouse_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY        NOT NULL,
                           warehouse_code VARCHAR2(50)  NOT NULL,
                           warehouse_name VARCHAR2(200) NOT NULL,
                           region_code    VARCHAR2(30),
                           address        VARCHAR2(500),
                           active_yn      CHAR(1) DEFAULT 'Y' NOT NULL,
                           CONSTRAINT pk_warehouse PRIMARY KEY (warehouse_id),
                           CONSTRAINT uq_warehouse_code UNIQUE (warehouse_code),
                           CONSTRAINT ck_warehouse_active CHECK (active_yn IN ('Y', 'N'))
);

CREATE TABLE app_role (
                          role_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY        NOT NULL,
                          role_code VARCHAR2(50)  NOT NULL,
                          role_name VARCHAR2(100) NOT NULL,
                          CONSTRAINT pk_app_role PRIMARY KEY (role_id),
                          CONSTRAINT uq_app_role_code UNIQUE (role_code)
);

CREATE TABLE supplier (
                          supplier_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY        NOT NULL,
                          supplier_code VARCHAR2(50)  NOT NULL,
                          supplier_name VARCHAR2(200) NOT NULL,
                          active_yn     CHAR(1) DEFAULT 'Y' NOT NULL,
                          CONSTRAINT pk_supplier PRIMARY KEY (supplier_id),
                          CONSTRAINT uq_supplier_code UNIQUE (supplier_code),
                          CONSTRAINT ck_supplier_active CHECK (active_yn IN ('Y', 'N'))
);

CREATE TABLE ingredient (
                            ingredient_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY        NOT NULL,
                            ingredient_name     VARCHAR2(100) NOT NULL,
                            ingredient_category VARCHAR2(50),
                            active_yn           CHAR(1) DEFAULT 'Y' NOT NULL,
                            CONSTRAINT pk_ingredient PRIMARY KEY (ingredient_id),
                            CONSTRAINT ck_ingredient_active CHECK (active_yn IN ('Y', 'N'))
);

CREATE TABLE category (
                          category_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY        NOT NULL,
                          parent_category_id NUMBER,
                          category_code      VARCHAR2(50)  NOT NULL,
                          category_name      VARCHAR2(200) NOT NULL,
                          category_level     NUMBER(2)     NOT NULL,
                          active_yn          CHAR(1) DEFAULT 'Y' NOT NULL,
                          source             VARCHAR2(30)  NOT NULL,
                          CONSTRAINT pk_category PRIMARY KEY (category_id),
                          CONSTRAINT uq_category_code UNIQUE (category_code),
                          CONSTRAINT fk_category_parent FOREIGN KEY (parent_category_id)
                              REFERENCES category (category_id),
                          CONSTRAINT ck_category_level CHECK (category_level IN (1, 2, 3)),
                          CONSTRAINT ck_category_active CHECK (active_yn IN ('Y', 'N')),
                          CONSTRAINT ck_category_source CHECK (source IN ('HI', 'GREETING'))
);

CREATE TABLE sales_point (
                             sales_point_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY        NOT NULL,
                             sales_channel_id NUMBER        NOT NULL,
                             sales_point_code VARCHAR2(50)  NOT NULL,
                             sales_point_name VARCHAR2(200) NOT NULL,
                             region_code      VARCHAR2(30),
                             address          VARCHAR2(500),
                             active_yn        CHAR(1) DEFAULT 'Y' NOT NULL,
                             CONSTRAINT pk_sales_point PRIMARY KEY (sales_point_id),
                             CONSTRAINT uq_sales_point_code UNIQUE (sales_point_code),
                             CONSTRAINT fk_sales_point_channel FOREIGN KEY (sales_channel_id)
                                 REFERENCES sales_channel (sales_channel_id),
                             CONSTRAINT ck_sales_point_active CHECK (active_yn IN ('Y', 'N'))
);

CREATE TABLE app_user (
                          user_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY        NOT NULL,
                          organization_id NUMBER        NOT NULL,
                          login_id        VARCHAR2(100) NOT NULL,
                          password_hash   VARCHAR2(255) NOT NULL,
                          user_name       VARCHAR2(100) NOT NULL,
                          email           VARCHAR2(255),
                          active_yn       CHAR(1) DEFAULT 'Y' NOT NULL,
                          last_login_at   TIMESTAMP,
                          CONSTRAINT pk_app_user PRIMARY KEY (user_id),
                          CONSTRAINT uq_app_user_login_id UNIQUE (login_id),
                          CONSTRAINT fk_app_user_organization FOREIGN KEY (organization_id)
                              REFERENCES organization (organization_id),
                          CONSTRAINT ck_user_active CHECK (active_yn IN ('Y', 'N'))
);

CREATE TABLE user_role (
                           user_role_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                           user_id      NUMBER NOT NULL,
                           role_id      NUMBER NOT NULL,
                           CONSTRAINT pk_user_role PRIMARY KEY (user_role_id),
                           CONSTRAINT uq_user_role UNIQUE (user_id, role_id),
                           CONSTRAINT fk_user_role_user FOREIGN KEY (user_id)
                               REFERENCES app_user (user_id),
                           CONSTRAINT fk_user_role_role FOREIGN KEY (role_id)
                               REFERENCES app_role (role_id)
);

CREATE TABLE user_access_scope (
                                   access_scope_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                                   user_id         NUMBER NOT NULL,
                                   warehouse_id    NUMBER NOT NULL,
                                   sales_point_id  NUMBER NOT NULL,
                                   revenue_view_yn CHAR(1) DEFAULT 'N' NOT NULL,
                                   CONSTRAINT pk_user_access_scope PRIMARY KEY (access_scope_id),
                                   CONSTRAINT fk_access_scope_user FOREIGN KEY (user_id)
                                       REFERENCES app_user (user_id),
                                   CONSTRAINT fk_access_scope_warehouse FOREIGN KEY (warehouse_id)
                                       REFERENCES warehouse (warehouse_id),
                                   CONSTRAINT fk_access_scope_sales_point FOREIGN KEY (sales_point_id)
                                       REFERENCES sales_point (sales_point_id),
                                   CONSTRAINT ck_access_scope_revenue CHECK (revenue_view_yn IN ('Y', 'N'))
);

CREATE TABLE audit_log (
                           audit_log_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY       NOT NULL,
                           user_id          NUMBER       NOT NULL,
                           action_type      VARCHAR2(50) NOT NULL,
                           entity_type      VARCHAR2(50) NOT NULL,
                           entity_id        NUMBER,
                           before_value_json CLOB,
                           after_value_json  CLOB,
                           client_ip        VARCHAR2(45),
                           CONSTRAINT pk_audit_log PRIMARY KEY (audit_log_id),
                           CONSTRAINT fk_audit_log_user FOREIGN KEY (user_id)
                               REFERENCES app_user (user_id),
                           CONSTRAINT ck_audit_log_action CHECK (
                               action_type IN ('CREATE', 'READ', 'UPDATE', 'DELETE', 'LOGIN', 'EXPORT')
                               )
);

CREATE TABLE sales_point_warehouse (
                                       sales_point_warehouse_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY       NOT NULL,
                                       sales_point_id           NUMBER       NOT NULL,
                                       warehouse_id             NUMBER       NOT NULL,
                                       priority_no              NUMBER(5),
                                       base_delivery_cost       NUMBER(18,2),
                                       active_yn                CHAR(1) DEFAULT 'Y' NOT NULL,
                                       CONSTRAINT pk_sales_point_warehouse PRIMARY KEY (sales_point_warehouse_id),
                                       CONSTRAINT uq_sales_point_warehouse UNIQUE (sales_point_id, warehouse_id),
                                       CONSTRAINT fk_spw_sales_point FOREIGN KEY (sales_point_id)
                                           REFERENCES sales_point (sales_point_id),
                                       CONSTRAINT fk_spw_warehouse FOREIGN KEY (warehouse_id)
                                           REFERENCES warehouse (warehouse_id),
                                       CONSTRAINT ck_spw_active CHECK (active_yn IN ('Y', 'N'))
);

CREATE TABLE product (
                         product_id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY        NOT NULL,
                         category_id             NUMBER        NOT NULL,
                         supplier_id             NUMBER,
                         product_code            VARCHAR2(50)  NOT NULL,
                         product_name            VARCHAR2(200) NOT NULL,
                         brand_name              VARCHAR2(100),
                         product_status          VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
                         sale_available_yn       CHAR(1) DEFAULT 'Y' NOT NULL,
                         manufactured_product_yn CHAR(1) DEFAULT 'N' NOT NULL,
                         CONSTRAINT pk_product PRIMARY KEY (product_id),
                         CONSTRAINT uq_product_code UNIQUE (product_code),
                         CONSTRAINT fk_product_category FOREIGN KEY (category_id)
                             REFERENCES category (category_id),
                         CONSTRAINT fk_product_supplier FOREIGN KEY (supplier_id)
                             REFERENCES supplier (supplier_id),
                         CONSTRAINT ck_product_status CHECK (product_status IN ('DRAFT', 'ACTIVE', 'INACTIVE')),
                         CONSTRAINT ck_product_sale CHECK (sale_available_yn IN ('Y', 'N')),
                         CONSTRAINT ck_product_manufactured CHECK (manufactured_product_yn IN ('Y', 'N'))
);

CREATE TABLE product_ingredient (
                                    product_ingredient_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                                    ingredient_id         NUMBER NOT NULL,
                                    product_id            NUMBER NOT NULL,
                                    main_ingredient_yn    CHAR(1) DEFAULT 'N' NOT NULL,
                                    CONSTRAINT pk_product_ingredient PRIMARY KEY (product_ingredient_id),
                                    CONSTRAINT uq_product_ingredient UNIQUE (product_id, ingredient_id),
                                    CONSTRAINT fk_prod_ing_ingredient FOREIGN KEY (ingredient_id)
                                        REFERENCES ingredient (ingredient_id),
                                    CONSTRAINT fk_prod_ing_product FOREIGN KEY (product_id)
                                        REFERENCES product (product_id),
                                    CONSTRAINT ck_prod_ing_main CHECK (main_ingredient_yn IN ('Y', 'N'))
);

CREATE TABLE sku (
                     sku_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY        NOT NULL,
                     product_id       NUMBER        NOT NULL,
                     sku_code         VARCHAR2(50)  NOT NULL,
                     sku_name         VARCHAR2(200) NOT NULL,
                     net_weight       NUMBER(12,3),
                     weight_unit      VARCHAR2(20),
                     package_quantity NUMBER(12,3) DEFAULT 1 NOT NULL,
                     unit_code        VARCHAR2(20)  NOT NULL,
                     storage_type     VARCHAR2(30) DEFAULT 'FROZEN',
                     active_yn        CHAR(1) DEFAULT 'Y' NOT NULL,
                     CONSTRAINT pk_sku PRIMARY KEY (sku_id),
                     CONSTRAINT uq_sku_code UNIQUE (sku_code),
                     CONSTRAINT fk_sku_product FOREIGN KEY (product_id)
                         REFERENCES product (product_id),
                     CONSTRAINT ck_sku_storage CHECK (storage_type IN ('FROZEN', 'AMBIENT')),
                     CONSTRAINT ck_sku_active CHECK (active_yn IN ('Y', 'N'))
);

CREATE TABLE lot (
                     lot_id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY        NOT NULL,
                     sku_id            NUMBER        NOT NULL,
                     lot_no            VARCHAR2(100) NOT NULL,
                     manufactured_date DATE,
                     received_date     DATE,
                     expiry_date       DATE,
                     sale_stop_date    DATE,
                     lot_status        VARCHAR2(30)  NOT NULL,
                     CONSTRAINT pk_lot PRIMARY KEY (lot_id),
                     CONSTRAINT uq_lot_no UNIQUE (lot_no),
                     CONSTRAINT fk_lot_sku FOREIGN KEY (sku_id)
                         REFERENCES sku (sku_id),
                     CONSTRAINT ck_lot_status CHECK (
                         lot_status IN ('AVAILABLE', 'SALE_STOPPED', 'EXPIRED', 'DEPLETED')
                         )
);

CREATE TABLE ml_model_version (
                                  model_version_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                                  model_name              VARCHAR2(100)  NOT NULL,
                                  model_version           VARCHAR2(50)   NOT NULL,
                                  algorithm_type          VARCHAR2(50)   NOT NULL,
                                  feature_definition_json CLOB,
                                  training_start_date     DATE,
                                  training_end_date       DATE,
                                  training_row_count      NUMBER,
                                  mae                     NUMBER(15,6),
                                  rmse                    NUMBER(15,6),
                                  status                  VARCHAR2(30)   NOT NULL,
                                  azure_model_uri         VARCHAR2(1000),
                                  created_at              TIMESTAMP      NOT NULL,
                                  CONSTRAINT pk_ml_model_version PRIMARY KEY (model_version_id),
                                  CONSTRAINT uq_ml_model_name_version UNIQUE (model_name, model_version),
                                  CONSTRAINT ck_ml_model_status CHECK (
                                      status IN ('TRAINING', 'VALIDATED', 'ACTIVE', 'REJECTED', 'ARCHIVED')
                                      )
);

CREATE TABLE ml_training_run (
                                 training_run_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                                 model_version_id NUMBER NULL,

                                 trigger_type     VARCHAR2(30) NOT NULL,

                                 data_from        DATE NOT NULL,
                                 data_to          DATE NOT NULL,

                                 started_at       TIMESTAMP NOT NULL,
                                 finished_at      TIMESTAMP,

                                 run_status       VARCHAR2(30) NOT NULL,

                                 azure_run_id     VARCHAR2(200),
                                 error_message    VARCHAR2(2000),

                                 CONSTRAINT pk_ml_training_run
                                     PRIMARY KEY (training_run_id),

                                 CONSTRAINT fk_ml_run_model_version
                                     FOREIGN KEY (model_version_id)
                                         REFERENCES ml_model_version (model_version_id),

                                 CONSTRAINT ck_ml_run_trigger
                                     CHECK (trigger_type IN (
                                                             'INITIAL',
                                                             'SCHEDULED',
                                                             'MANUAL'
                                         )),

                                 CONSTRAINT ck_ml_run_status
                                     CHECK (run_status IN (
                                                           'RUNNING',
                                                           'SUCCESS',
                                                           'FAILED'
                                         ))
);

CREATE TABLE demand_forecast (
                                 forecast_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                                 sku_id          NUMBER       NOT NULL,
                                 sales_point_id  NUMBER       NOT NULL,
                                 model_version_id NUMBER      NOT NULL,
                                 base_date       DATE         NOT NULL,
                                 forecast_from   DATE         NOT NULL,
                                 forecast_to     DATE         NOT NULL,
                                 predicted_qty   NUMBER(15,3) NOT NULL,
                                 method_type     VARCHAR2(30) NOT NULL,
                                 CONSTRAINT pk_demand_forecast PRIMARY KEY (forecast_id),
                                 CONSTRAINT fk_forecast_sku FOREIGN KEY (sku_id)
                                     REFERENCES sku (sku_id),
                                 CONSTRAINT fk_forecast_sales_point FOREIGN KEY (sales_point_id)
                                     REFERENCES sales_point (sales_point_id),
                                 CONSTRAINT fk_forecast_model FOREIGN KEY (model_version_id)
                                     REFERENCES ml_model_version (model_version_id)
);

CREATE TABLE sales_daily (
                             sales_daily_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY       NOT NULL,
                             sku_id           NUMBER       NOT NULL,
                             sales_point_id   NUMBER       NOT NULL,
                             sales_date       DATE         NOT NULL,
                             net_sales_qty    NUMBER(15,3) DEFAULT 0 NOT NULL,
                             net_sales_amount NUMBER(18,2) DEFAULT 0 NOT NULL,
                             CONSTRAINT pk_sales_daily PRIMARY KEY (sales_daily_id),
                             CONSTRAINT uq_sales_daily UNIQUE (sku_id, sales_point_id, sales_date),
                             CONSTRAINT fk_sales_daily_sku FOREIGN KEY (sku_id)
                                 REFERENCES sku (sku_id),
                             CONSTRAINT fk_sales_daily_point FOREIGN KEY (sales_point_id)
                                 REFERENCES sales_point (sales_point_id)
);

CREATE TABLE sku_channel_price (
                                   sku_channel_price_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY       NOT NULL,
                                   sku_id                NUMBER       NOT NULL,
                                   sales_point_id        NUMBER       NOT NULL,
                                   selling_price         NUMBER(18,2) NOT NULL,
                                   minimum_selling_price NUMBER(18,2),
                                   actual_price          NUMBER(18,2) NOT NULL,
                                   product_cost          NUMBER(18,2) NOT NULL,
                                   payment_fee           NUMBER(18,2),
                                   packaging_cost        NUMBER(18,2),
                                   logistics_cost        NUMBER(18,2),
                                   effective_from        DATE         NOT NULL,
                                   effective_to          DATE,
                                   CONSTRAINT pk_sku_channel_price PRIMARY KEY (sku_channel_price_id),
                                   CONSTRAINT fk_sku_price_sku FOREIGN KEY (sku_id)
                                       REFERENCES sku (sku_id),
                                   CONSTRAINT fk_sku_price_sales_point FOREIGN KEY (sales_point_id)
                                       REFERENCES sales_point (sales_point_id)
);

CREATE TABLE inventory_balance (
                                   inventory_balance_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY       NOT NULL,
                                   sku_id                   NUMBER       NOT NULL,
                                   warehouse_id             NUMBER,
                                   stock_sales_point_id     NUMBER,
                                   allocated_sales_point_id NUMBER,
                                   lot_id                   NUMBER,
                                   on_hand_qty              NUMBER(15,3) DEFAULT 0 NOT NULL,
                                   reserved_qty             NUMBER(15,3) DEFAULT 0 NOT NULL,
                                   total_qty                NUMBER(15,3) DEFAULT 0 NOT NULL,
                                   CONSTRAINT pk_inventory_balance PRIMARY KEY (inventory_balance_id),
                                   CONSTRAINT fk_inv_balance_sku FOREIGN KEY (sku_id)
                                       REFERENCES sku (sku_id),
                                   CONSTRAINT fk_inv_balance_warehouse FOREIGN KEY (warehouse_id)
                                       REFERENCES warehouse (warehouse_id),
                                   CONSTRAINT fk_inv_balance_stock_sp FOREIGN KEY (stock_sales_point_id)
                                       REFERENCES sales_point (sales_point_id),
                                   CONSTRAINT fk_inv_balance_alloc_sp FOREIGN KEY (allocated_sales_point_id)
                                       REFERENCES sales_point (sales_point_id),
                                   CONSTRAINT fk_inv_balance_lot FOREIGN KEY (lot_id)
                                       REFERENCES lot (lot_id)
);

CREATE TABLE inventory_policy (
                                  inventory_policy_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY       NOT NULL,
                                  sku_id                   NUMBER       NOT NULL,
                                  warehouse_id             NUMBER,
                                  stock_sales_point_id     NUMBER,
                                  allocated_sales_point_id NUMBER,
                                  safety_stock_qty         NUMBER(15,3) DEFAULT 0 NOT NULL,
                                  target_stock_qty         NUMBER(15,3),
                                  effective_from           DATE,
                                  effective_to             DATE,
                                  daily_unit_holding_cost  NUMBER(18,4),
                                  unit_disposal_cost       NUMBER(18,2),
                                  CONSTRAINT pk_inventory_policy PRIMARY KEY (inventory_policy_id),
                                  CONSTRAINT fk_inv_policy_sku FOREIGN KEY (sku_id)
                                      REFERENCES sku (sku_id),
                                  CONSTRAINT fk_inv_policy_warehouse FOREIGN KEY (warehouse_id)
                                      REFERENCES warehouse (warehouse_id),
                                  CONSTRAINT fk_inv_policy_stock_sp FOREIGN KEY (stock_sales_point_id)
                                      REFERENCES sales_point (sales_point_id),
                                  CONSTRAINT fk_inv_policy_alloc_sp FOREIGN KEY (allocated_sales_point_id)
                                      REFERENCES sales_point (sales_point_id)
);

CREATE TABLE risk_assessment (
                                 risk_assessment_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY         NOT NULL,
                                 inventory_balance_id NUMBER        NOT NULL,
                                 forecast_id         NUMBER,
                                 risk_grade          VARCHAR2(20)   NOT NULL,
                                 shortage_yn         CHAR(1) DEFAULT 'N' NOT NULL,
                                 stock_days          NUMBER(10,2),
                                 holding_days        NUMBER(10),
                                 expiry_days_left    NUMBER(10),
                                 rule_version        VARCHAR2(100),
                                 reason_message      VARCHAR2(1000) NOT NULL,
                                 CONSTRAINT pk_risk_assessment PRIMARY KEY (risk_assessment_id),
                                 CONSTRAINT fk_risk_inventory_balance FOREIGN KEY (inventory_balance_id)
                                     REFERENCES inventory_balance (inventory_balance_id),
                                 CONSTRAINT fk_risk_forecast FOREIGN KEY (forecast_id)
                                     REFERENCES demand_forecast (forecast_id),
                                 CONSTRAINT ck_risk_grade CHECK (risk_grade IN ('CRITICAL', 'WARNING', 'NORMAL', 'GOOD')),
                                 CONSTRAINT ck_risk_shortage CHECK (shortage_yn IN ('Y', 'N'))
);

CREATE TABLE strategy_case (
                               strategy_case_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY       NOT NULL,
                               sku_id                   NUMBER       NOT NULL,
                               created_by               NUMBER       NOT NULL,
                               requested_sales_point_id NUMBER,
                               case_code                VARCHAR2(50) NOT NULL,
                               primary_objective        VARCHAR2(50) NOT NULL,
                               case_status              VARCHAR2(30) NOT NULL,
                               CONSTRAINT pk_strategy_case PRIMARY KEY (strategy_case_id),
                               CONSTRAINT uq_strategy_case_code UNIQUE (case_code),
                               CONSTRAINT fk_strategy_case_sku FOREIGN KEY (sku_id)
                                   REFERENCES sku (sku_id),
                               CONSTRAINT fk_strategy_case_user FOREIGN KEY (created_by)
                                   REFERENCES app_user (user_id),
                               CONSTRAINT fk_strategy_case_point FOREIGN KEY (requested_sales_point_id)
                                   REFERENCES sales_point (sales_point_id),
                               CONSTRAINT ck_strategy_case_objective CHECK (
                                   primary_objective IN ('CLEARANCE', 'NET_MARGIN_MAX', 'MAX_REVENUE')
                                   ),
                               CONSTRAINT ck_strategy_case_status CHECK (
                                   case_status IN (
                                                   'GENERATING', 'GENERATED', 'GENERATION_FAILED',
                                                   'READY_TO_EXECUTE', 'EXECUTING', 'EXECUTION_COMPLETED'
                                       )
                                   )
);

CREATE TABLE strategy_option (
                                 strategy_option_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY         NOT NULL,
                                 strategy_case_id      NUMBER         NOT NULL,
                                 option_rank           NUMBER(2)      NOT NULL,
                                 option_name           VARCHAR2(200)  NOT NULL,
                                 recommendation_reason VARCHAR2(2000),
                                 advantage_text        VARCHAR2(2000),
                                 caution_text          VARCHAR2(2000),
                                 constraint_text       VARCHAR2(2000),
                                 CONSTRAINT pk_strategy_option PRIMARY KEY (strategy_option_id),
                                 CONSTRAINT fk_strategy_option_case FOREIGN KEY (strategy_case_id)
                                     REFERENCES strategy_case (strategy_case_id)
);

CREATE TABLE strategy_simulation (
                                     simulation_id                  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY       NOT NULL,
                                     strategy_option_id             NUMBER       NOT NULL,
                                     input_source_type              VARCHAR2(30) NOT NULL,
                                     target_quantity                NUMBER(15,3),
                                     strategy_price                 NUMBER(18,2),
                                     coupon_cost                    NUMBER(18,2),
                                     delivery_cost                  NUMBER(18,2),
                                     movement_cost                  NUMBER(18,2),
                                     expected_sales_qty             NUMBER(15,3),
                                     expected_revenue               NUMBER(18,2),
                                     unit_contribution_margin       NUMBER(18,2),
                                     contribution_margin_rate       NUMBER(10,6),
                                     total_contribution_margin      NUMBER(18,2),
                                     expected_remaining_qty         NUMBER(15,3),
                                     avoided_disposal_cost          NUMBER(18,2),
                                     CONSTRAINT pk_strategy_simulation PRIMARY KEY (simulation_id),
                                     CONSTRAINT fk_strategy_sim_option FOREIGN KEY (strategy_option_id)
                                         REFERENCES strategy_option (strategy_option_id),
                                     CONSTRAINT ck_strategy_sim_source CHECK (
                                         input_source_type IN ('AI_RECOMMENDED', 'USER_SELECT')
                                         )
);

CREATE TABLE strategy_action (
                                 strategy_action_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY       NOT NULL,
                                 strategy_option_id      NUMBER       NOT NULL,
                                 sales_point_id          NUMBER       NOT NULL,
                                 source_warehouse_id     NUMBER,
                                 destination_warehouse_id NUMBER,
                                 action_type             VARCHAR2(30) NOT NULL,
                                 action_quantity         NUMBER(15,3),
                                 strategy_price          NUMBER(18,2),
                                 discount_rate           NUMBER(7,4),
                                 start_date              DATE,
                                 end_date                DATE,
                                 estimated_action_cost   NUMBER(18,2),
                                 action_order            NUMBER(5),
                                 CONSTRAINT pk_strategy_action PRIMARY KEY (strategy_action_id),
                                 CONSTRAINT fk_strategy_action_option FOREIGN KEY (strategy_option_id)
                                     REFERENCES strategy_option (strategy_option_id),
                                 CONSTRAINT fk_strategy_action_point FOREIGN KEY (sales_point_id)
                                     REFERENCES sales_point (sales_point_id),
                                 CONSTRAINT fk_strategy_action_src_wh FOREIGN KEY (source_warehouse_id)
                                     REFERENCES warehouse (warehouse_id),
                                 CONSTRAINT fk_strategy_action_dst_wh FOREIGN KEY (destination_warehouse_id)
                                     REFERENCES warehouse (warehouse_id),
                                 CONSTRAINT ck_strategy_action_type CHECK (
                                     action_type IN (
                                                     'REALLOCATION', 'RT_TRANSFER', 'PRICE_DISCOUNT', 'COUPON',
                                                     'POINT_REWARD', 'FREE_SHIPPING', 'PROMOTION_STOP',
                                                     'CHANNEL_EXPANSION', 'CHANNEL_CONCENTRATION'
                                         )
                                     )
);

CREATE TABLE strategy_lot_allocation (
                                         lot_allocation_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY       NOT NULL,
                                         lot_id               NUMBER       NOT NULL,
                                         allocated_quantity   NUMBER(15,3) NOT NULL,
                                         priority_no          NUMBER(5)    NOT NULL,
                                         source_warehouse_id  NUMBER,
                                         source_sales_point_id NUMBER,
                                         strategy_action_id   NUMBER       NOT NULL,
                                         CONSTRAINT pk_strategy_lot_allocation PRIMARY KEY (lot_allocation_id),
                                         CONSTRAINT fk_lot_alloc_lot FOREIGN KEY (lot_id)
                                             REFERENCES lot (lot_id),
                                         CONSTRAINT fk_lot_alloc_warehouse FOREIGN KEY (source_warehouse_id)
                                             REFERENCES warehouse (warehouse_id),
                                         CONSTRAINT fk_lot_alloc_sales_point FOREIGN KEY (source_sales_point_id)
                                             REFERENCES sales_point (sales_point_id),
                                         CONSTRAINT fk_lot_alloc_action FOREIGN KEY (strategy_action_id)
                                             REFERENCES strategy_action (strategy_action_id)
);

CREATE TABLE strategy_review_request (
                                         review_request_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY         NOT NULL,
                                         strategy_option_id NUMBER,
                                         requester_id       NUMBER         NOT NULL,
                                         reviewer_id        NUMBER         NOT NULL,
                                         review_status      VARCHAR2(30)   NOT NULL,
                                         teams_message_id   VARCHAR2(200),
                                         strategy_url       VARCHAR2(1000),
                                         reviewed_at        TIMESTAMP,
                                         CONSTRAINT pk_strategy_review_request PRIMARY KEY (review_request_id),
                                         CONSTRAINT fk_review_request_option FOREIGN KEY (strategy_option_id)
                                             REFERENCES strategy_option (strategy_option_id),
                                         CONSTRAINT fk_review_request_requester FOREIGN KEY (requester_id)
                                             REFERENCES app_user (user_id),
                                         CONSTRAINT fk_review_request_reviewer FOREIGN KEY (reviewer_id)
                                             REFERENCES app_user (user_id),
                                         CONSTRAINT ck_review_request_status CHECK (review_status IN ('PENDING', 'SENT', 'FAILED'))
);

CREATE TABLE strategy_performance (
                                      strategy_performance_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY       NOT NULL,
                                      strategy_option_id           NUMBER       NOT NULL,
                                      performance_date             DATE         NOT NULL,
                                      actual_sales_qty             NUMBER(15,3) DEFAULT 0 NOT NULL,
                                      actual_revenue               NUMBER(18,2) DEFAULT 0 NOT NULL,
                                      actual_contribution_margin   NUMBER(18,2) DEFAULT 0 NOT NULL,
                                      actual_remaining_qty         NUMBER(15,3) DEFAULT 0 NOT NULL,
                                      moved_quantity               NUMBER(15,3) DEFAULT 0 NOT NULL,
                                      disposed_quantity            NUMBER(15,3) DEFAULT 0 NOT NULL,
                                      achievement_rate             NUMBER(10,6),
                                      CONSTRAINT pk_strategy_performance PRIMARY KEY (strategy_performance_id),
                                      CONSTRAINT fk_strategy_perf_option FOREIGN KEY (strategy_option_id)
                                          REFERENCES strategy_option (strategy_option_id)
);

CREATE TABLE strategy_inventory_snapshot (
                                             inventory_snapshot_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY       NOT NULL,
                                             strategy_case_id      NUMBER       NOT NULL,
                                             sku_id                NUMBER       NOT NULL,
                                             lot_id                NUMBER       NOT NULL,
                                             sales_point_id        NUMBER       NOT NULL,
                                             inventory_balance_id  NUMBER       NOT NULL,
                                             on_total_qty          NUMBER(15,3) NOT NULL,
                                             on_hand_qty           NUMBER(15,3) NOT NULL,
                                             safety_stock_qty      NUMBER(15,3) DEFAULT 0 NOT NULL,
                                             daily_sales_velocity  NUMBER(15,3),
                                             forecast_qty          NUMBER(15,3),
                                             expiry_date           DATE,
                                             warehouse_id          NUMBER       NOT NULL,
                                             CONSTRAINT pk_strategy_inventory_snapshot PRIMARY KEY (inventory_snapshot_id),
                                             CONSTRAINT fk_strat_snap_case FOREIGN KEY (strategy_case_id)
                                                 REFERENCES strategy_case (strategy_case_id),
                                             CONSTRAINT fk_strat_snap_sku FOREIGN KEY (sku_id)
                                                 REFERENCES sku (sku_id),
                                             CONSTRAINT fk_strat_snap_lot FOREIGN KEY (lot_id)
                                                 REFERENCES lot (lot_id),
                                             CONSTRAINT fk_strat_snap_sales_point FOREIGN KEY (sales_point_id)
                                                 REFERENCES sales_point (sales_point_id),
                                             CONSTRAINT fk_strat_snap_inv_balance FOREIGN KEY (inventory_balance_id)
                                                 REFERENCES inventory_balance (inventory_balance_id),
                                             CONSTRAINT fk_strat_snap_warehouse FOREIGN KEY (warehouse_id)
                                                 REFERENCES warehouse (warehouse_id)
);

CREATE TABLE final_strategy_selection (
                                          final_selection_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                                          strategy_case_id    NUMBER NOT NULL,
                                          strategy_option_id  NUMBER NOT NULL,
                                          created_by          NUMBER NOT NULL,
                                          CONSTRAINT pk_final_strategy_selection PRIMARY KEY (final_selection_id),
                                          CONSTRAINT fk_final_selection_case FOREIGN KEY (strategy_case_id)
                                              REFERENCES strategy_case (strategy_case_id),
                                          CONSTRAINT fk_final_selection_option FOREIGN KEY (strategy_option_id)
                                              REFERENCES strategy_option (strategy_option_id),
                                          CONSTRAINT fk_final_selection_user FOREIGN KEY (created_by)
                                              REFERENCES app_user (user_id)
);

CREATE TABLE strategy_price_snapshot (
                                         price_snapshot_id                  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY       NOT NULL,
                                         strategy_case_id                   NUMBER       NOT NULL,
                                         sku_id                             NUMBER       NOT NULL,
                                         sales_point_id                     NUMBER       NOT NULL,
                                         current_price                      NUMBER(18,2) NOT NULL,
                                         product_cost                       NUMBER(18,2),
                                         payment_fee                        NUMBER(18,2),
                                         packaging_cost                     NUMBER(18,2),
                                         logistics_cost                     NUMBER(18,2),
                                         unit_variable_cost                 NUMBER(18,2),
                                         baseline_unit_contribution_margin  NUMBER(18,2),
                                         CONSTRAINT pk_strategy_price_snapshot PRIMARY KEY (price_snapshot_id),
                                         CONSTRAINT fk_price_snapshot_case FOREIGN KEY (strategy_case_id)
                                             REFERENCES strategy_case (strategy_case_id),
                                         CONSTRAINT fk_price_snapshot_sku FOREIGN KEY (sku_id)
                                             REFERENCES sku (sku_id),
                                         CONSTRAINT fk_price_snapshot_point FOREIGN KEY (sales_point_id)
                                             REFERENCES sales_point (sales_point_id)
);

CREATE TABLE notification (
                              notification_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY         NOT NULL,
                              user_id         NUMBER         NOT NULL,
                              strategy_case_id NUMBER        NOT NULL,
                              title           VARCHAR2(200)  NOT NULL,
                              message         VARCHAR2(1000) NOT NULL,
                              read_yn         CHAR(1) DEFAULT 'N' NOT NULL,
                              read_at         TIMESTAMP,
                              CONSTRAINT pk_notification PRIMARY KEY (notification_id),
                              CONSTRAINT fk_notification_user FOREIGN KEY (user_id)
                                  REFERENCES app_user (user_id),
                              CONSTRAINT fk_notification_case FOREIGN KEY (strategy_case_id)
                                  REFERENCES strategy_case (strategy_case_id),
                              CONSTRAINT ck_notification_read CHECK (read_yn IN ('Y', 'N'))
);

-- Column comments retained from the ERD. ASCII-only text is used to avoid encoding issues.
COMMENT ON COLUMN organization.organization_type IS
    'Allowed organization types: HEAD_OFFICE, ONLINE_CHANNEL, OFFLINE_STORE, WAREHOUSE';
COMMENT ON COLUMN sales_channel.channel_type IS
    'Allowed channel types: ONLINE, OFFLINE';
COMMENT ON COLUMN sales_channel.active_yn IS
    'Active flag. Allowed values: Y, N';
COMMENT ON COLUMN strategy_simulation.input_source_type IS
    'Input source. Allowed values: AI_RECOMMENDED, USER_SELECT';
COMMENT ON COLUMN strategy_simulation.unit_contribution_margin IS
    'Expected contribution margin per unit sold';
COMMENT ON COLUMN strategy_simulation.avoided_disposal_cost IS
    'Estimated disposal cost avoided through sales';
COMMENT ON COLUMN strategy_case.case_code IS
    'Unique strategy case code';
COMMENT ON COLUMN strategy_case.primary_objective IS
    'Primary objective. Allowed values: CLEARANCE, NET_MARGIN_MAX, MAX_REVENUE';
COMMENT ON COLUMN strategy_case.case_status IS
    'Case status. Allowed values: GENERATING, GENERATED, GENERATION_FAILED, READY_TO_EXECUTE, EXECUTING, EXECUTION_COMPLETED';
COMMENT ON COLUMN strategy_review_request.review_status IS
    'Review request status. Allowed values: PENDING, SENT, FAILED';
COMMENT ON COLUMN user_access_scope.revenue_view_yn IS
    'Revenue viewing permission flag. Allowed values: Y, N. C-level users should use Y';
COMMENT ON COLUMN audit_log.action_type IS
    'Audit action. Allowed values: CREATE, READ, UPDATE, DELETE, LOGIN, EXPORT';
COMMENT ON COLUMN audit_log.entity_type IS
    'Type or name of the target entity table';
COMMENT ON COLUMN audit_log.entity_id IS
    'Primary key value of the target entity';
COMMENT ON COLUMN sales_point_warehouse.active_yn IS
    'Active flag. Allowed values: Y, N';
COMMENT ON COLUMN warehouse.active_yn IS
    'Active flag. Allowed values: Y, N';
COMMENT ON COLUMN app_role.role_code IS
    'Unique role code';
COMMENT ON COLUMN strategy_action.action_type IS
    'Action type. Allowed values: REALLOCATION, RT_TRANSFER, PRICE_DISCOUNT, COUPON, POINT_REWARD, FREE_SHIPPING, PROMOTION_STOP, CHANNEL_EXPANSION, CHANNEL_CONCENTRATION';
COMMENT ON COLUMN risk_assessment.risk_grade IS
    'Risk grade. Allowed values: CRITICAL, WARNING, NORMAL, GOOD';
COMMENT ON COLUMN risk_assessment.shortage_yn IS
    'Shortage flag. Allowed values: Y, N. Set to Y when stock is below safety stock';
COMMENT ON COLUMN risk_assessment.holding_days IS
    'Calculated holding period in days from the received date';
COMMENT ON COLUMN sku.sku_code IS
    'Unique SKU code';
COMMENT ON COLUMN sku.storage_type IS
    'Storage type. Allowed values: FROZEN, AMBIENT';
COMMENT ON COLUMN sku.active_yn IS
    'Active flag. Allowed values: Y, N';
COMMENT ON COLUMN app_user.active_yn IS
    'Active flag. Allowed values: Y, N';
COMMENT ON COLUMN supplier.supplier_code IS
    'Unique supplier code';
COMMENT ON COLUMN supplier.active_yn IS
    'Active flag. Allowed values: Y, N';
COMMENT ON COLUMN inventory_balance.total_qty IS
    'Total quantity. Source ERD formula: on_hand_qty + reserved_qty';
COMMENT ON COLUMN final_strategy_selection.final_selection_id IS
    'Final strategy selection identifier';
COMMENT ON COLUMN product_ingredient.main_ingredient_yn IS
    'Main ingredient flag. Allowed values: Y, N';
COMMENT ON COLUMN product.product_code IS
    'Unique product code';
COMMENT ON COLUMN product.product_status IS
    'Product status. Allowed values: DRAFT, ACTIVE, INACTIVE';
COMMENT ON COLUMN product.sale_available_yn IS
    'Sale availability flag. Allowed values: Y, N';
COMMENT ON COLUMN product.manufactured_product_yn IS
    'Manufactured product flag. Allowed values: Y, N';
COMMENT ON COLUMN category.category_code IS
    'Unique category code';
COMMENT ON COLUMN category.category_level IS
    'Category hierarchy level: 1 major, 2 middle, 3 minor';
COMMENT ON COLUMN category.active_yn IS
    'Active flag. Allowed values: Y, N';
COMMENT ON COLUMN category.source IS
    'Category source. Allowed values: HI, GREETING';
COMMENT ON COLUMN strategy_price_snapshot.unit_variable_cost IS
    'Unit variable cost: product cost + payment fee + packaging cost + logistics cost';
COMMENT ON COLUMN strategy_price_snapshot.baseline_unit_contribution_margin IS
    'Baseline unit contribution margin: current price - unit variable cost';
COMMENT ON COLUMN lot.lot_no IS
    'Unique lot number';
COMMENT ON COLUMN lot.lot_status IS
    'Lot status. Allowed values: AVAILABLE, SALE_STOPPED, EXPIRED, DEPLETED';
COMMENT ON COLUMN notification.read_yn IS
    'Read flag. Allowed values: Y, N';
COMMENT ON COLUMN ingredient.active_yn IS
    'Active flag. Allowed values: Y, N';
COMMENT ON COLUMN sales_point.active_yn IS
    'Active flag. Allowed values: Y, N';
COMMENT ON COLUMN ml_model_version.status IS
    'Model status. Allowed values: TRAINING, VALIDATED, ACTIVE, REJECTED, ARCHIVED';
COMMENT ON COLUMN ml_training_run.trigger_type IS
    'Training trigger. Allowed values: INITIAL, SCHEDULED, PERFORMANCE_DROP, MANUAL';
COMMIT;