-- V21: Source-specific current data and durable manual synchronization control.
-- V1-V20 are intentionally not rewritten. Apply only after the approved Oracle preflight.

CREATE TABLE inventory_sync_mutex (
    mutex_id NUMBER(1) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_inventory_sync_mutex PRIMARY KEY (mutex_id),
    CONSTRAINT ck_inventory_sync_mutex_singleton CHECK (mutex_id = 1)
);
INSERT INTO inventory_sync_mutex (mutex_id) VALUES (1);

CREATE TABLE inventory_sync_run (
    inventory_sync_run_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    client_request_id           VARCHAR2(80) NOT NULL,
    request_hash                CHAR(64) NOT NULL,
    trigger_type                VARCHAR2(20) DEFAULT 'MANUAL' NOT NULL,
    run_status                  VARCHAR2(30) NOT NULL,
    current_phase               VARCHAR2(30),
    active_scope_key            VARCHAR2(50),
    fencing_token               NUMBER(19) DEFAULT 1 NOT NULL,
    main_batch_job_execution_id NUMBER(19),
    main_attempt_no             NUMBER(10) DEFAULT 0 NOT NULL,
    lease_owner_instance_id     VARCHAR2(200),
    requested_by                NUMBER NOT NULL,
    requested_at                TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    started_at                  TIMESTAMP,
    heartbeat_at                TIMESTAMP,
    lease_expires_at            TIMESTAMP,
    completed_at                TIMESTAMP,
    read_count                  NUMBER(19) DEFAULT 0 NOT NULL,
    mapped_count                NUMBER(19) DEFAULT 0 NOT NULL,
    changed_count               NUMBER(19) DEFAULT 0 NOT NULL,
    error_count                 NUMBER(19) DEFAULT 0 NOT NULL,
    error_code                  VARCHAR2(100),
    error_message               VARCHAR2(2000),
    created_at                  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at                  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_inventory_sync_run PRIMARY KEY (inventory_sync_run_id),
    CONSTRAINT uq_isync_client_request UNIQUE (client_request_id),
    CONSTRAINT uq_isync_active_scope UNIQUE (active_scope_key),
    CONSTRAINT fk_isync_requested_by FOREIGN KEY (requested_by) REFERENCES app_user (user_id),
    CONSTRAINT ck_isync_trigger CHECK (trigger_type IN ('MANUAL')),
    CONSTRAINT ck_isync_status CHECK (run_status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SOURCE_CHANGED', 'INTERRUPTED', 'LAUNCH_FAILED')),
    CONSTRAINT ck_isync_phase CHECK (current_phase IS NULL OR current_phase IN ('READING', 'NORMALIZING', 'VALIDATING', 'PUBLISHING', 'ASSESSING_RISK')),
    CONSTRAINT ck_isync_active_scope CHECK (active_scope_key IS NULL OR active_scope_key = 'INVENTORY_CANONICAL'),
    CONSTRAINT ck_isync_counts CHECK (read_count >= 0 AND mapped_count >= 0 AND changed_count >= 0 AND error_count >= 0),
    CONSTRAINT ck_isync_attempt CHECK (main_attempt_no >= 0 AND fencing_token > 0)
);

CREATE INDEX ix_isync_request_rate ON inventory_sync_run (requested_by, requested_at);
CREATE INDEX ix_isync_status ON inventory_sync_run (run_status, requested_at);

CREATE TABLE inventory_source_offline (
    inventory_source_offline_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    source_record_key          VARCHAR2(300) NOT NULL,
    offline_source_code        VARCHAR2(30) NOT NULL,
    branch_code                VARCHAR2(50) NOT NULL,
    branch_name                VARCHAR2(200),
    sales_channel_code         VARCHAR2(30),
    item_no                    VARCHAR2(100) NOT NULL,
    item_name                  VARCHAR2(300),
    category_large_name        VARCHAR2(200), category_middle_name VARCHAR2(200), category_small_name VARCHAR2(200),
    brand_label                VARCHAR2(150), merchandise_state_code VARCHAR2(30), sale_flag CHAR(1),
    branch_option_no           VARCHAR2(100) NOT NULL, branch_option_name VARCHAR2(300), package_spec_text VARCHAR2(300),
    content_value              NUMBER(15,3), content_unit_label VARCHAR2(30), sell_pack_count NUMBER(15,3), sell_unit_label VARCHAR2(30),
    storage_method_text        VARCHAR2(30), tag_price_amount NUMBER(18,2), store_sale_price_amount NUMBER(18,2), store_unit_cost_amount NUMBER(18,2),
    price_valid_from           DATE, price_valid_to DATE, supply_center_code VARCHAR2(50), supply_center_name VARCHAR2(200),
    store_lot_number           VARCHAR2(120) NOT NULL, made_date_text VARCHAR2(30), received_date_text VARCHAR2(30), use_by_date_text VARCHAR2(30),
    sale_stop_date_text        VARCHAR2(30), store_lot_state_code VARCHAR2(30), available_stock_count NUMBER(15,3) NOT NULL,
    reserved_stock_count       NUMBER(15,3) DEFAULT 0 NOT NULL, safe_stock_count NUMBER(15,3), target_stock_count NUMBER(15,3),
    display_sold_out_flag      CHAR(1), customer_review_count NUMBER(15,3), customer_rating_score NUMBER(15,3),
    image_link                 VARCHAR2(1000), product_link VARCHAR2(1000), expiry_guide_text VARCHAR2(1000),
    record_hash                CHAR(64) NOT NULL, row_version NUMBER(19) DEFAULT 1 NOT NULL, synced_record_hash CHAR(64), last_sync_run_id NUMBER,
    fixture_generation_id      VARCHAR2(80) NOT NULL, fixture_rule_version VARCHAR2(50) NOT NULL, source_modified_at TIMESTAMP, last_synced_at TIMESTAMP,
    active_yn                 CHAR(1) DEFAULT 'Y' NOT NULL, is_deleted NUMBER(1) DEFAULT 0 NOT NULL,
    created_at                TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    created_by                NUMBER NOT NULL, updated_by NUMBER NOT NULL,
    CONSTRAINT pk_isrc_offline PRIMARY KEY (inventory_source_offline_id),
    CONSTRAINT uq_isrc_offline_key UNIQUE (source_record_key),
    CONSTRAINT fk_isrc_offline_run FOREIGN KEY (last_sync_run_id) REFERENCES inventory_sync_run (inventory_sync_run_id) ON DELETE SET NULL,
    CONSTRAINT fk_isrc_offline_created FOREIGN KEY (created_by) REFERENCES app_user (user_id),
    CONSTRAINT fk_isrc_offline_updated FOREIGN KEY (updated_by) REFERENCES app_user (user_id),
    CONSTRAINT ck_isrc_off_source CHECK (offline_source_code IN ('HYUNDAI_DEPT', 'HMART_DIRECT')),
    CONSTRAINT ck_isrc_off_flag CHECK (sale_flag IS NULL OR sale_flag IN ('Y', 'N')),
    CONSTRAINT ck_isrc_off_active CHECK (active_yn IN ('Y', 'N') AND is_deleted IN (0, 1)),
    CONSTRAINT ck_isrc_off_qty CHECK (available_stock_count >= 0 AND reserved_stock_count >= 0)
);

CREATE TABLE inventory_source_ecommerce (
    inventory_source_ecommerce_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    source_record_key            VARCHAR2(300) NOT NULL,
    mall_code VARCHAR2(50) NOT NULL, online_store_code VARCHAR2(50) NOT NULL, online_store_name VARCHAR2(200), seller_product_no VARCHAR2(100) NOT NULL,
    display_product_title VARCHAR2(300), display_category_path VARCHAR2(500), seller_brand_label VARCHAR2(150), catalog_state_code VARCHAR2(30),
    seller_option_no VARCHAR2(100) NOT NULL, seller_option_name VARCHAR2(300), option_spec_text VARCHAR2(300), content_amount NUMBER(15,3),
    order_pack_count NUMBER(15,3), content_uom_label VARCHAR2(30), order_unit_label VARCHAR2(30), delivery_temperature_code VARCHAR2(30), option_enabled_flag CHAR(1),
    display_list_price NUMBER(18,2), discounted_sale_price NUMBER(18,2), payment_fee_amount NUMBER(18,2), delivery_cost_amount NUMBER(18,2), seller_unit_cost_amount NUMBER(18,2),
    price_started_on DATE, price_ended_on DATE, fulfillment_center_code VARCHAR2(50), fulfillment_center_name VARCHAR2(200), inventory_batch_code VARCHAR2(120) NOT NULL,
    made_on_text VARCHAR2(30), stocked_on_text VARCHAR2(30), expires_on_text VARCHAR2(30), blocked_on_text VARCHAR2(30), batch_state_code VARCHAR2(30),
    sellable_quantity NUMBER(15,3) NOT NULL, ordered_quantity NUMBER(15,3) DEFAULT 0 NOT NULL, safety_quantity NUMBER(15,3), target_quantity NUMBER(15,3),
    listing_state_code VARCHAR2(30), display_discount_rate NUMBER(10,4), review_total_count NUMBER(15,3), rating_average NUMBER(15,3), thumbnail_link VARCHAR2(1000), detail_page_link VARCHAR2(1000), expiry_notice_text VARCHAR2(1000),
    record_hash CHAR(64) NOT NULL, row_version NUMBER(19) DEFAULT 1 NOT NULL, synced_record_hash CHAR(64), last_sync_run_id NUMBER,
    fixture_generation_id VARCHAR2(80) NOT NULL, fixture_rule_version VARCHAR2(50) NOT NULL, source_modified_at TIMESTAMP, last_synced_at TIMESTAMP,
    active_yn CHAR(1) DEFAULT 'Y' NOT NULL, is_deleted NUMBER(1) DEFAULT 0 NOT NULL, created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    created_by NUMBER NOT NULL, updated_by NUMBER NOT NULL,
    CONSTRAINT pk_isrc_ecommerce PRIMARY KEY (inventory_source_ecommerce_id), CONSTRAINT uq_isrc_ecommerce_key UNIQUE (source_record_key),
    CONSTRAINT fk_isrc_ecom_run FOREIGN KEY (last_sync_run_id) REFERENCES inventory_sync_run (inventory_sync_run_id) ON DELETE SET NULL,
    CONSTRAINT fk_isrc_ecom_created FOREIGN KEY (created_by) REFERENCES app_user (user_id), CONSTRAINT fk_isrc_ecom_updated FOREIGN KEY (updated_by) REFERENCES app_user (user_id),
    CONSTRAINT ck_isrc_ecom_flag CHECK (option_enabled_flag IS NULL OR option_enabled_flag IN ('Y', 'N')),
    CONSTRAINT ck_isrc_ecom_active CHECK (active_yn IN ('Y', 'N') AND is_deleted IN (0, 1)), CONSTRAINT ck_isrc_ecom_qty CHECK (sellable_quantity >= 0 AND ordered_quantity >= 0)
);

CREATE TABLE inventory_source_greeting (
    inventory_source_greeting_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    source_record_key VARCHAR2(300) NOT NULL, greeting_shop_code VARCHAR2(50) NOT NULL, greeting_shop_name VARCHAR2(200), greeting_item_id VARCHAR2(100) NOT NULL, menu_name VARCHAR2(300),
    menu_group_large VARCHAR2(200), menu_group_middle VARCHAR2(200), menu_group_small VARCHAR2(200), maker_name VARCHAR2(150), brand_display_name VARCHAR2(150), menu_sale_state VARCHAR2(30),
    greeting_sku_id VARCHAR2(100) NOT NULL, greeting_sku_name VARCHAR2(300), serving_spec_text VARCHAR2(300), net_content_amount NUMBER(15,3), package_count NUMBER(15,3), net_content_unit_label VARCHAR2(30), sale_unit_label VARCHAR2(30), cold_chain_type VARCHAR2(30),
    normal_price_amount NUMBER(18,2), member_price_amount NUMBER(18,2), payment_fee_amount NUMBER(18,2), shipping_cost_amount NUMBER(18,2), menu_unit_cost_amount NUMBER(18,2), membership_price_from DATE, membership_price_to DATE,
    operation_center_code VARCHAR2(50), operation_center_name VARCHAR2(200), production_batch_no VARCHAR2(120) NOT NULL, cooked_date_text VARCHAR2(30), received_date_text VARCHAR2(30), consume_by_text VARCHAR2(30), sale_block_date_text VARCHAR2(30), production_batch_state VARCHAR2(30),
    saleable_meal_count NUMBER(15,3) NOT NULL, committed_meal_count NUMBER(15,3) DEFAULT 0 NOT NULL, minimum_stock_count NUMBER(15,3), target_stock_count NUMBER(15,3), sold_out_flag CHAR(1), review_count NUMBER(15,3), rating_score NUMBER(15,3), thumbnail_link VARCHAR2(1000), menu_page_link VARCHAR2(1000), shelf_life_guide VARCHAR2(1000),
    record_hash CHAR(64) NOT NULL, row_version NUMBER(19) DEFAULT 1 NOT NULL, synced_record_hash CHAR(64), last_sync_run_id NUMBER, fixture_generation_id VARCHAR2(80) NOT NULL, fixture_rule_version VARCHAR2(50) NOT NULL, source_modified_at TIMESTAMP, last_synced_at TIMESTAMP,
    active_yn CHAR(1) DEFAULT 'Y' NOT NULL, is_deleted NUMBER(1) DEFAULT 0 NOT NULL, created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, created_by NUMBER NOT NULL, updated_by NUMBER NOT NULL,
    CONSTRAINT pk_isrc_greeting PRIMARY KEY (inventory_source_greeting_id), CONSTRAINT uq_isrc_greeting_key UNIQUE (source_record_key),
    CONSTRAINT fk_isrc_greet_run FOREIGN KEY (last_sync_run_id) REFERENCES inventory_sync_run (inventory_sync_run_id) ON DELETE SET NULL,
    CONSTRAINT fk_isrc_greet_created FOREIGN KEY (created_by) REFERENCES app_user (user_id), CONSTRAINT fk_isrc_greet_updated FOREIGN KEY (updated_by) REFERENCES app_user (user_id),
    CONSTRAINT ck_isrc_greet_flag CHECK (sold_out_flag IS NULL OR sold_out_flag IN ('Y', 'N')), CONSTRAINT ck_isrc_greet_active CHECK (active_yn IN ('Y', 'N') AND is_deleted IN (0, 1)), CONSTRAINT ck_isrc_greet_qty CHECK (saleable_meal_count >= 0 AND committed_meal_count >= 0)
);

CREATE TABLE inventory_source_warehouse (
    inventory_source_warehouse_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    source_record_key VARCHAR2(300) NOT NULL, logistics_center_code VARCHAR2(50) NOT NULL, logistics_center_name VARCHAR2(200), center_item_key VARCHAR2(150) NOT NULL, center_product_code VARCHAR2(100) NOT NULL, center_product_name VARCHAR2(300),
    goods_category_code VARCHAR2(50), goods_category_name VARCHAR2(500), goods_brand_name VARCHAR2(150), goods_state_code VARCHAR2(30), center_sku_code VARCHAR2(100) NOT NULL, center_sku_name VARCHAR2(300), stock_unit_code VARCHAR2(30), stock_net_weight NUMBER(15,3), stock_weight_unit VARCHAR2(30), units_per_case NUMBER(15,3), temperature_zone_code VARCHAR2(30), standard_unit_cost NUMBER(18,2), assigned_sales_point_code VARCHAR2(50),
    center_lot_number VARCHAR2(120) NOT NULL, manufactured_date_text VARCHAR2(30), inbound_date_text VARCHAR2(30), expiry_date_text VARCHAR2(30), shipping_stop_date_text VARCHAR2(30), lot_quality_state VARCHAR2(30), physical_available_qty NUMBER(15,3) NOT NULL, physical_reserved_qty NUMBER(15,3) DEFAULT 0 NOT NULL, center_safety_qty NUMBER(15,3), center_target_qty NUMBER(15,3), inventory_condition_code VARCHAR2(30), last_stocktake_at TIMESTAMP,
    record_hash CHAR(64) NOT NULL, row_version NUMBER(19) DEFAULT 1 NOT NULL, synced_record_hash CHAR(64), last_sync_run_id NUMBER, fixture_generation_id VARCHAR2(80) NOT NULL, fixture_rule_version VARCHAR2(50) NOT NULL, source_modified_at TIMESTAMP, last_synced_at TIMESTAMP,
    active_yn CHAR(1) DEFAULT 'Y' NOT NULL, is_deleted NUMBER(1) DEFAULT 0 NOT NULL, created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, created_by NUMBER NOT NULL, updated_by NUMBER NOT NULL,
    CONSTRAINT pk_isrc_warehouse PRIMARY KEY (inventory_source_warehouse_id), CONSTRAINT uq_isrc_warehouse_key UNIQUE (source_record_key),
    CONSTRAINT fk_isrc_wh_run FOREIGN KEY (last_sync_run_id) REFERENCES inventory_sync_run (inventory_sync_run_id) ON DELETE SET NULL,
    CONSTRAINT fk_isrc_wh_created FOREIGN KEY (created_by) REFERENCES app_user (user_id), CONSTRAINT fk_isrc_wh_updated FOREIGN KEY (updated_by) REFERENCES app_user (user_id),
    CONSTRAINT ck_isrc_wh_unassigned CHECK (assigned_sales_point_code IS NULL), CONSTRAINT ck_isrc_wh_active CHECK (active_yn IN ('Y', 'N') AND is_deleted IN (0, 1)), CONSTRAINT ck_isrc_wh_qty CHECK (physical_available_qty >= 0 AND physical_reserved_qty >= 0)
);

CREATE TABLE inventory_source_row_map (
    source_row_map_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL, source_type VARCHAR2(20) NOT NULL, source_record_key VARCHAR2(300) NOT NULL,
    product_id NUMBER, sku_id NUMBER, sales_point_id NUMBER, warehouse_id NUMBER, lot_id NUMBER, inventory_balance_id NUMBER, sku_channel_price_id NUMBER, sku_cost_id NUMBER, inventory_policy_id NUMBER,
    mapping_method VARCHAR2(30) DEFAULT 'INITIAL_EXACT' NOT NULL, mapping_status VARCHAR2(30) DEFAULT 'MAPPED' NOT NULL, mapping_version VARCHAR2(50) NOT NULL, validated_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, created_by NUMBER NOT NULL, updated_by NUMBER NOT NULL, is_deleted NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT pk_isrc_map PRIMARY KEY (source_row_map_id), CONSTRAINT uq_isrc_map_key UNIQUE (source_type, source_record_key),
    CONSTRAINT fk_isrc_map_product FOREIGN KEY (product_id) REFERENCES product (product_id), CONSTRAINT fk_isrc_map_sku FOREIGN KEY (sku_id) REFERENCES sku (sku_id),
    CONSTRAINT fk_isrc_map_sales_point FOREIGN KEY (sales_point_id) REFERENCES sales_point (sales_point_id), CONSTRAINT fk_isrc_map_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouse (warehouse_id),
    CONSTRAINT fk_isrc_map_lot FOREIGN KEY (lot_id) REFERENCES lot (lot_id), CONSTRAINT fk_isrc_map_balance FOREIGN KEY (inventory_balance_id) REFERENCES inventory_balance (inventory_balance_id),
    CONSTRAINT fk_isrc_map_price FOREIGN KEY (sku_channel_price_id) REFERENCES sku_channel_price (sku_channel_price_id), CONSTRAINT fk_isrc_map_cost FOREIGN KEY (sku_cost_id) REFERENCES sku_cost (sku_cost_id), CONSTRAINT fk_isrc_map_policy FOREIGN KEY (inventory_policy_id) REFERENCES inventory_policy (inventory_policy_id),
    CONSTRAINT fk_isrc_map_created FOREIGN KEY (created_by) REFERENCES app_user (user_id), CONSTRAINT fk_isrc_map_updated FOREIGN KEY (updated_by) REFERENCES app_user (user_id),
    CONSTRAINT ck_isrc_map_type CHECK (source_type IN ('OFFLINE', 'ECOMMERCE', 'GREETING', 'WAREHOUSE')), CONSTRAINT ck_isrc_map_method CHECK (mapping_method IN ('INITIAL_EXACT', 'APPROVED_MANUAL')), CONSTRAINT ck_isrc_map_status CHECK (mapping_status IN ('MAPPED', 'INVALID', 'REVIEW_REQUIRED')), CONSTRAINT ck_isrc_map_deleted CHECK (is_deleted IN (0, 1))
);

CREATE TABLE inventory_source_state (
    source_type VARCHAR2(20) NOT NULL, current_version NUMBER(19) DEFAULT 1 NOT NULL, current_record_count NUMBER(19) DEFAULT 0 NOT NULL, pending_record_count NUMBER(19) DEFAULT 0 NOT NULL,
    last_verified_checksum CHAR(64), checksum_verified_version NUMBER(19), last_changed_at TIMESTAMP, last_success_sync_run_id NUMBER, last_success_synced_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, created_by NUMBER NOT NULL, updated_by NUMBER NOT NULL,
    CONSTRAINT pk_isrc_state PRIMARY KEY (source_type), CONSTRAINT fk_isrc_state_run FOREIGN KEY (last_success_sync_run_id) REFERENCES inventory_sync_run (inventory_sync_run_id) ON DELETE SET NULL,
    CONSTRAINT fk_isrc_state_created FOREIGN KEY (created_by) REFERENCES app_user (user_id), CONSTRAINT fk_isrc_state_updated FOREIGN KEY (updated_by) REFERENCES app_user (user_id),
    CONSTRAINT ck_isrc_state_type CHECK (source_type IN ('OFFLINE', 'ECOMMERCE', 'GREETING', 'WAREHOUSE')), CONSTRAINT ck_isrc_state_counts CHECK (current_version > 0 AND current_record_count >= 0 AND pending_record_count >= 0)
);

CREATE TABLE inventory_sync_run_source (
    inventory_sync_run_source_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL, inventory_sync_run_id NUMBER NOT NULL, source_type VARCHAR2(20) NOT NULL,
    start_version NUMBER(19) NOT NULL, end_version NUMBER(19), start_checksum CHAR(64), end_checksum CHAR(64), source_status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    read_count NUMBER(19) DEFAULT 0 NOT NULL, mapped_count NUMBER(19) DEFAULT 0 NOT NULL, changed_count NUMBER(19) DEFAULT 0 NOT NULL, error_count NUMBER(19) DEFAULT 0 NOT NULL, started_at TIMESTAMP, completed_at TIMESTAMP,
    CONSTRAINT pk_isync_run_source PRIMARY KEY (inventory_sync_run_source_id), CONSTRAINT uq_isync_run_source UNIQUE (inventory_sync_run_id, source_type), CONSTRAINT fk_isync_run_source_run FOREIGN KEY (inventory_sync_run_id) REFERENCES inventory_sync_run (inventory_sync_run_id) ON DELETE CASCADE,
    CONSTRAINT ck_isync_run_source_type CHECK (source_type IN ('OFFLINE', 'ECOMMERCE', 'GREETING', 'WAREHOUSE')), CONSTRAINT ck_isync_run_source_status CHECK (source_status IN ('PENDING', 'RUNNING', 'SUCCESS', 'FAILED')), CONSTRAINT ck_isync_run_source_counts CHECK (read_count >= 0 AND mapped_count >= 0 AND changed_count >= 0 AND error_count >= 0)
);

CREATE TABLE inventory_sync_error (
    inventory_sync_error_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL, inventory_sync_run_id NUMBER NOT NULL, source_type VARCHAR2(20) NOT NULL, source_record_key VARCHAR2(300), error_phase VARCHAR2(30) NOT NULL, field_name VARCHAR2(100), error_code VARCHAR2(100) NOT NULL, error_message VARCHAR2(2000) NOT NULL, created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_isync_error PRIMARY KEY (inventory_sync_error_id), CONSTRAINT fk_isync_error_run FOREIGN KEY (inventory_sync_run_id) REFERENCES inventory_sync_run (inventory_sync_run_id) ON DELETE CASCADE, CONSTRAINT ck_isync_error_type CHECK (source_type IN ('OFFLINE', 'ECOMMERCE', 'GREETING', 'WAREHOUSE'))
);

CREATE INDEX ix_isrc_off_sync ON inventory_source_offline (synced_record_hash, row_version);
CREATE INDEX ix_isrc_ecom_sync ON inventory_source_ecommerce (synced_record_hash, row_version);
CREATE INDEX ix_isrc_greet_sync ON inventory_source_greeting (synced_record_hash, row_version);
CREATE INDEX ix_isrc_wh_sync ON inventory_source_warehouse (synced_record_hash, row_version);
CREATE INDEX ix_isrc_map_balance ON inventory_source_row_map (inventory_balance_id, mapping_status);
CREATE INDEX ix_isync_error_run ON inventory_sync_error (inventory_sync_run_id, source_type);
