-- V23: Local/demo-only source adjustment audit. No canonical table is changed here.
CREATE TABLE inventory_demo_adjustment (
    inventory_demo_adjustment_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    request_id VARCHAR2(80) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    source_type VARCHAR2(20) NOT NULL,
    source_record_key VARCHAR2(300) NOT NULL,
    decrease_qty NUMBER(15,3) NOT NULL,
    source_row_version_before NUMBER(19) NOT NULL,
    source_row_version_after NUMBER(19),
    source_hash_before CHAR(64) NOT NULL,
    source_hash_after CHAR(64),
    adjustment_status VARCHAR2(20) DEFAULT 'APPLIED' NOT NULL,
    requested_by NUMBER NOT NULL,
    requested_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    applied_at TIMESTAMP,
    payload_json CLOB NOT NULL,
    error_code VARCHAR2(100),
    error_message VARCHAR2(1000),
    CONSTRAINT pk_inventory_demo_adjustment PRIMARY KEY (inventory_demo_adjustment_id),
    CONSTRAINT uq_inventory_demo_item_request UNIQUE (request_id, source_type, source_record_key),
    CONSTRAINT fk_demo_adjustment_user FOREIGN KEY (requested_by) REFERENCES app_user (user_id),
    CONSTRAINT ck_demo_adjustment_source CHECK (source_type IN ('OFFLINE', 'ECOMMERCE', 'GREETING', 'WAREHOUSE')),
    CONSTRAINT ck_demo_adjustment_qty CHECK (decrease_qty > 0),
    CONSTRAINT ck_demo_adjustment_status CHECK (adjustment_status IN ('APPLIED', 'REJECTED')),
    CONSTRAINT ck_demo_adjustment_payload CHECK (payload_json IS JSON)
);

CREATE INDEX ix_demo_adjustment_rate ON inventory_demo_adjustment (requested_by, requested_at);
CREATE INDEX ix_demo_adjustment_source ON inventory_demo_adjustment (source_type, source_record_key, requested_at);
