-- V25: Durable daily demand-forecast orchestration and atomic publication.
-- FastAPI batches are isolated in staging until the complete result set is received.

CREATE TABLE demand_forecast_run (
    forecast_run_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    client_request_id       VARCHAR2(80) NOT NULL,
    schedule_key            VARCHAR2(50),
    trigger_type            VARCHAR2(20) DEFAULT 'SCHEDULED' NOT NULL,
    base_date               DATE NOT NULL,
    model_version_id        NUMBER,
    azure_job_id            VARCHAR2(255),
    input_blob_url          VARCHAR2(1000),
    dataset_hash            CHAR(64),
    run_status              VARCHAR2(30) NOT NULL,
    current_stage           VARCHAR2(30),
    export_job_execution_id NUMBER(19),
    total_batches           NUMBER(10),
    total_items             NUMBER(19),
    received_batches        NUMBER(10) DEFAULT 0 NOT NULL,
    received_items          NUMBER(19) DEFAULT 0 NOT NULL,
    submitted_at            TIMESTAMP,
    last_polled_at          TIMESTAMP,
    import_requested_at     TIMESTAMP,
    all_batches_received_at TIMESTAMP,
    started_at              TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    completed_at            TIMESTAMP,
    error_code              VARCHAR2(100),
    error_message           VARCHAR2(2000),
    created_at              TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at              TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    created_by              NUMBER NOT NULL,
    updated_by              NUMBER NOT NULL,
    is_deleted              NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT pk_df_run PRIMARY KEY (forecast_run_id),
    CONSTRAINT uq_df_run_request UNIQUE (client_request_id),
    CONSTRAINT uq_df_run_schedule UNIQUE (schedule_key),
    CONSTRAINT uq_df_run_azure UNIQUE (azure_job_id),
    CONSTRAINT fk_df_run_model FOREIGN KEY (model_version_id)
        REFERENCES ml_model_version (model_version_id),
    CONSTRAINT fk_df_run_created FOREIGN KEY (created_by)
        REFERENCES app_user (user_id),
    CONSTRAINT fk_df_run_updated FOREIGN KEY (updated_by)
        REFERENCES app_user (user_id),
    CONSTRAINT ck_df_run_trigger CHECK (
        trigger_type IN ('SCHEDULED', 'MANUAL', 'RETRY')
    ),
    CONSTRAINT ck_df_run_status CHECK (
        run_status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'TIMED_OUT', 'CANCELED')
    ),
    CONSTRAINT ck_df_run_stage CHECK (
        current_stage IS NULL OR current_stage IN (
            'EXPORTING', 'UPLOADING', 'AZURE_SUBMITTING', 'AZURE_POLLING',
            'IMPORT_REQUESTING', 'IMPORTING', 'FINALIZING'
        )
    ),
    CONSTRAINT ck_df_run_counts CHECK (
        received_batches >= 0
        AND received_items >= 0
        AND (total_batches IS NULL OR total_batches > 0)
        AND (total_items IS NULL OR total_items > 0)
        AND (total_batches IS NULL OR received_batches <= total_batches)
        AND (total_items IS NULL OR received_items <= total_items)
    ),
    CONSTRAINT ck_df_run_deleted CHECK (is_deleted IN (0, 1))
);

CREATE INDEX ix_df_run_status
    ON demand_forecast_run (run_status, current_stage, started_at);
CREATE INDEX ix_df_run_base_date
    ON demand_forecast_run (base_date, started_at);

CREATE TABLE demand_forecast_import_batch (
    forecast_import_batch_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    forecast_run_id          NUMBER NOT NULL,
    batch_number             NUMBER(10) NOT NULL,
    item_count               NUMBER(10) NOT NULL,
    payload_hash             CHAR(64) NOT NULL,
    received_at              TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    created_at               TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    created_by               NUMBER NOT NULL,
    CONSTRAINT pk_df_import_batch PRIMARY KEY (forecast_import_batch_id),
    CONSTRAINT uq_df_import_batch UNIQUE (forecast_run_id, batch_number),
    CONSTRAINT fk_df_import_batch_run FOREIGN KEY (forecast_run_id)
        REFERENCES demand_forecast_run (forecast_run_id) ON DELETE CASCADE,
    CONSTRAINT fk_df_import_batch_user FOREIGN KEY (created_by)
        REFERENCES app_user (user_id),
    CONSTRAINT ck_df_import_batch_no CHECK (batch_number >= 1),
    CONSTRAINT ck_df_import_batch_count CHECK (item_count BETWEEN 1 AND 1000)
);

CREATE TABLE demand_forecast_staging (
    forecast_staging_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    forecast_run_id     NUMBER NOT NULL,
    batch_number        NUMBER(10) NOT NULL,
    sku_id              NUMBER NOT NULL,
    sales_point_id      NUMBER NOT NULL,
    predicted_qty_d7    NUMBER(15,3) NOT NULL,
    predicted_qty_d14   NUMBER(15,3) NOT NULL,
    predicted_qty_d30   NUMBER(15,3) NOT NULL,
    predicted_qty_d60   NUMBER(15,3) NOT NULL,
    predicted_qty_d90   NUMBER(15,3) NOT NULL,
    forecast_source     VARCHAR2(40) NOT NULL,
    confidence_level    VARCHAR2(10) NOT NULL,
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    created_by          NUMBER NOT NULL,
    CONSTRAINT pk_df_staging PRIMARY KEY (forecast_staging_id),
    CONSTRAINT uq_df_staging_target UNIQUE (forecast_run_id, sku_id, sales_point_id),
    CONSTRAINT fk_df_staging_run FOREIGN KEY (forecast_run_id)
        REFERENCES demand_forecast_run (forecast_run_id) ON DELETE CASCADE,
    CONSTRAINT fk_df_staging_sku FOREIGN KEY (sku_id) REFERENCES sku (sku_id),
    CONSTRAINT fk_df_staging_point FOREIGN KEY (sales_point_id) REFERENCES sales_point (sales_point_id),
    CONSTRAINT fk_df_staging_user FOREIGN KEY (created_by) REFERENCES app_user (user_id),
    CONSTRAINT ck_df_staging_batch CHECK (batch_number >= 1),
    CONSTRAINT ck_df_staging_qty CHECK (
        predicted_qty_d7 >= 0
        AND predicted_qty_d7 <= predicted_qty_d14
        AND predicted_qty_d14 <= predicted_qty_d30
        AND predicted_qty_d30 <= predicted_qty_d60
        AND predicted_qty_d60 <= predicted_qty_d90
    ),
    CONSTRAINT ck_df_staging_source CHECK (
        forecast_source IN (
            'LIGHTGBM', 'SAME_SKU_OTHER_POINT', 'CATEGORY_SALES_POINT_MEDIAN',
            'CATEGORY_GLOBAL_MEDIAN', 'MANUAL_INITIAL', 'DUMMY_BASELINE'
        )
    ),
    CONSTRAINT ck_df_staging_conf CHECK (confidence_level IN ('HIGH', 'MEDIUM', 'LOW'))
);

CREATE INDEX ix_df_staging_batch
    ON demand_forecast_staging (forecast_run_id, batch_number);

-- Existing forecasts predate orchestration and intentionally keep a NULL run reference.
ALTER TABLE demand_forecast ADD (forecast_run_id NUMBER);
ALTER TABLE demand_forecast ADD CONSTRAINT fk_df_forecast_run
    FOREIGN KEY (forecast_run_id) REFERENCES demand_forecast_run (forecast_run_id);
CREATE INDEX ix_df_forecast_run ON demand_forecast (forecast_run_id);

COMMENT ON TABLE demand_forecast_run IS 'Daily demand forecast orchestration execution';
COMMENT ON TABLE demand_forecast_import_batch IS 'Idempotent FastAPI forecast batch receipt';
COMMENT ON TABLE demand_forecast_staging IS 'Unpublished forecast rows awaiting complete batch receipt';
COMMENT ON COLUMN demand_forecast.forecast_run_id IS 'Orchestration run that published this forecast';

-- Generalize the existing strategy-only notification table for pipeline alerts.
ALTER TABLE notification MODIFY (strategy_case_id NULL);
ALTER TABLE notification ADD (
    forecast_run_id   NUMBER,
    notification_type VARCHAR2(50),
    severity          VARCHAR2(10),
    deduplication_key VARCHAR2(200)
);

UPDATE notification
SET notification_type = 'STRATEGY_CASE',
    severity = 'INFO',
    deduplication_key = 'LEGACY:' || TO_CHAR(notification_id)
WHERE notification_type IS NULL;

ALTER TABLE notification MODIFY (
    notification_type NOT NULL,
    severity NOT NULL,
    deduplication_key NOT NULL
);

ALTER TABLE notification ADD CONSTRAINT fk_notification_df_run
    FOREIGN KEY (forecast_run_id) REFERENCES demand_forecast_run (forecast_run_id);
ALTER TABLE notification ADD CONSTRAINT ck_notification_severity
    CHECK (severity IN ('INFO', 'WARNING', 'ERROR'));
ALTER TABLE notification ADD CONSTRAINT ck_notification_reference
    CHECK (
        (strategy_case_id IS NOT NULL AND forecast_run_id IS NULL)
        OR (strategy_case_id IS NULL AND forecast_run_id IS NOT NULL)
    );
ALTER TABLE notification ADD CONSTRAINT uq_notification_dedupe
    UNIQUE (user_id, deduplication_key);
CREATE INDEX ix_notification_unread
    ON notification (user_id, read_yn, created_at);

COMMENT ON COLUMN notification.forecast_run_id IS 'Demand forecast run associated with a pipeline alert';
COMMENT ON COLUMN notification.notification_type IS 'Business notification event type';
COMMENT ON COLUMN notification.severity IS 'INFO, WARNING, or ERROR';
COMMENT ON COLUMN notification.deduplication_key IS 'Unique key preventing duplicate event delivery';
