-- V27: Durable dashboard/statistics follow-up tasks for inventory synchronization.
-- V21-V26 are immutable. This table stores bounded retry and restart recovery state.

CREATE TABLE inventory_sync_snapshot_task (
    inventory_sync_snapshot_task_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    inventory_sync_run_id           NUMBER NOT NULL,
    task_type                       VARCHAR2(30) NOT NULL,
    task_status                     VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    business_date                   DATE NOT NULL,
    attempt_count                   NUMBER(3) DEFAULT 0 NOT NULL,
    max_attempts                    NUMBER(3) DEFAULT 3 NOT NULL,
    next_attempt_at                 TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    lease_owner_instance_id         VARCHAR2(200),
    lease_expires_at                TIMESTAMP,
    started_at                      TIMESTAMP,
    completed_at                    TIMESTAMP,
    last_error_code                 VARCHAR2(100),
    last_error_message              VARCHAR2(2000),
    created_at                      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at                      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_isync_snapshot_task PRIMARY KEY (inventory_sync_snapshot_task_id),
    CONSTRAINT uq_isync_snapshot_task UNIQUE (inventory_sync_run_id, task_type),
    CONSTRAINT fk_isync_snapshot_task_run FOREIGN KEY (inventory_sync_run_id)
        REFERENCES inventory_sync_run (inventory_sync_run_id) ON DELETE CASCADE,
    CONSTRAINT ck_isync_snapshot_task_type CHECK (
        task_type IN ('DASHBOARD', 'INVENTORY_STATISTICS')
    ),
    CONSTRAINT ck_isync_snapshot_task_status CHECK (
        task_status IN ('PENDING', 'RUNNING', 'RETRY_WAIT', 'SUCCEEDED', 'FAILED')
    ),
    CONSTRAINT ck_isync_snapshot_attempts CHECK (
        attempt_count >= 0 AND max_attempts > 0 AND attempt_count <= max_attempts
    )
);

CREATE INDEX ix_isync_snapshot_task_due
    ON inventory_sync_snapshot_task (task_status, next_attempt_at, lease_expires_at);

COMMENT ON TABLE inventory_sync_snapshot_task
    IS '통합재고 변경 후 대시보드·재고통계 스냅샷의 bounded retry와 재시작 복구 상태';
COMMENT ON COLUMN inventory_sync_snapshot_task.task_type
    IS '후속 작업 종류: DASHBOARD, INVENTORY_STATISTICS';
COMMENT ON COLUMN inventory_sync_snapshot_task.task_status
    IS 'PENDING, RUNNING, RETRY_WAIT, SUCCEEDED, FAILED';
COMMENT ON COLUMN inventory_sync_snapshot_task.attempt_count
    IS 'DB claim에 성공해 실제 실행을 시작한 횟수';
COMMENT ON COLUMN inventory_sync_snapshot_task.next_attempt_at
    IS 'PENDING 또는 RETRY_WAIT 작업을 다시 claim할 수 있는 시각';
COMMENT ON COLUMN inventory_sync_snapshot_task.lease_expires_at
    IS 'RUNNING worker의 실행권 만료 시각. 만료 후 recovery 대상';
