-- RT_TRANSFER 후보가 물리적 이동 거리와 중량을 기준으로 예상 이동비를
-- 계산하고, 최종 선택 시 계산 근거를 보존할 수 있도록 스키마를 확장한다.
-- 경로 거리와 요율은 환경별 기준 데이터이므로 이 마이그레이션에 Seed하지 않는다.

CREATE TABLE inventory_transfer_route (
    transfer_route_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    route_code                 VARCHAR2(150) NOT NULL,
    source_location_type       VARCHAR2(20) NOT NULL,
    source_warehouse_id        NUMBER,
    source_sales_point_id      NUMBER,
    destination_location_type  VARCHAR2(20) NOT NULL,
    destination_warehouse_id   NUMBER,
    destination_sales_point_id NUMBER,
    distance_km                NUMBER(10,3) NOT NULL,
    distance_source            VARCHAR2(30) NOT NULL,
    distance_route_option      VARCHAR2(50),
    distance_calculated_at     TIMESTAMP,
    active_yn                  CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at                 TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at                 TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    created_by                 NUMBER NOT NULL,
    updated_by                 NUMBER NOT NULL,
    is_deleted                 NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT pk_inv_transfer_route PRIMARY KEY (transfer_route_id),
    CONSTRAINT uq_inv_transfer_route_code UNIQUE (route_code),
    CONSTRAINT fk_itr_source_warehouse FOREIGN KEY (source_warehouse_id)
        REFERENCES warehouse (warehouse_id),
    CONSTRAINT fk_itr_source_point FOREIGN KEY (source_sales_point_id)
        REFERENCES sales_point (sales_point_id),
    CONSTRAINT fk_itr_dest_warehouse FOREIGN KEY (destination_warehouse_id)
        REFERENCES warehouse (warehouse_id),
    CONSTRAINT fk_itr_dest_point FOREIGN KEY (destination_sales_point_id)
        REFERENCES sales_point (sales_point_id),
    CONSTRAINT fk_itr_created_by FOREIGN KEY (created_by)
        REFERENCES app_user (user_id),
    CONSTRAINT fk_itr_updated_by FOREIGN KEY (updated_by)
        REFERENCES app_user (user_id),
    CONSTRAINT ck_itr_source_location CHECK (
        (source_location_type = 'WAREHOUSE'
            AND source_warehouse_id IS NOT NULL
            AND source_sales_point_id IS NULL)
        OR
        (source_location_type = 'SALES_POINT'
            AND source_warehouse_id IS NULL
            AND source_sales_point_id IS NOT NULL)
    ),
    CONSTRAINT ck_itr_destination_loc CHECK (
        (destination_location_type = 'WAREHOUSE'
            AND destination_warehouse_id IS NOT NULL
            AND destination_sales_point_id IS NULL)
        OR
        (destination_location_type = 'SALES_POINT'
            AND destination_warehouse_id IS NULL
            AND destination_sales_point_id IS NOT NULL)
    ),
    CONSTRAINT ck_itr_not_same_location CHECK (
        source_location_type <> destination_location_type
        OR NVL(source_warehouse_id, source_sales_point_id)
            <> NVL(destination_warehouse_id, destination_sales_point_id)
    ),
    CONSTRAINT ck_itr_distance CHECK (distance_km > 0),
    CONSTRAINT ck_itr_active CHECK (active_yn IN ('Y', 'N')),
    CONSTRAINT ck_itr_deleted CHECK (is_deleted IN (0, 1))
);

-- 활성 상태의 동일 방향 경로는 하나만 존재해야 한다. 위치 유형과 ID를
-- 함께 사용하므로 warehouse_id와 sales_point_id가 같아도 다른 위치다.
CREATE UNIQUE INDEX uq_itr_active_path
    ON inventory_transfer_route (
        CASE WHEN active_yn = 'Y' AND is_deleted = 0
            THEN source_location_type END,
        CASE WHEN active_yn = 'Y' AND is_deleted = 0
            THEN NVL(source_warehouse_id, source_sales_point_id) END,
        CASE WHEN active_yn = 'Y' AND is_deleted = 0
            THEN destination_location_type END,
        CASE WHEN active_yn = 'Y' AND is_deleted = 0
            THEN NVL(destination_warehouse_id, destination_sales_point_id) END
    );

CREATE INDEX ix_itr_route_lookup
    ON inventory_transfer_route (
        source_location_type,
        source_warehouse_id,
        source_sales_point_id,
        destination_location_type,
        destination_warehouse_id,
        destination_sales_point_id,
        active_yn,
        is_deleted
    );

CREATE TABLE inventory_transfer_cost_policy (
    transfer_cost_policy_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    policy_code             VARCHAR2(50) NOT NULL,
    policy_name             VARCHAR2(100) NOT NULL,
    cost_per_kg_km          NUMBER(18,6) NOT NULL,
    effective_from          DATE NOT NULL,
    effective_to            DATE,
    active_yn               CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at              TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at              TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    created_by              NUMBER NOT NULL,
    updated_by              NUMBER NOT NULL,
    is_deleted              NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT pk_inv_transfer_cost_policy PRIMARY KEY (transfer_cost_policy_id),
    CONSTRAINT uq_inv_transfer_policy_code UNIQUE (policy_code),
    CONSTRAINT fk_itcp_created_by FOREIGN KEY (created_by)
        REFERENCES app_user (user_id),
    CONSTRAINT fk_itcp_updated_by FOREIGN KEY (updated_by)
        REFERENCES app_user (user_id),
    CONSTRAINT ck_itcp_cost CHECK (cost_per_kg_km > 0),
    CONSTRAINT ck_itcp_effective_range CHECK (
        effective_to IS NULL OR effective_to >= effective_from
    ),
    CONSTRAINT ck_itcp_active CHECK (active_yn IN ('Y', 'N')),
    CONSTRAINT ck_itcp_deleted CHECK (is_deleted IN (0, 1))
);

CREATE INDEX ix_itcp_effective_lookup
    ON inventory_transfer_cost_policy (
        active_yn,
        is_deleted,
        effective_from,
        effective_to
    );

ALTER TABLE strategy_action ADD (
    transfer_route_id            NUMBER,
    transfer_cost_policy_id      NUMBER,
    movement_cost_status         VARCHAR2(20) DEFAULT 'NOT_APPLICABLE',
    movement_weight_kg           NUMBER(18,6),
    movement_distance_km         NUMBER(10,3),
    movement_cost_per_kg_km      NUMBER(18,6)
);

-- 기존 RT_TRANSFER는 당시 거리·중량·요율을 복원할 수 없으므로 소급
-- 계산하지 않는다. 다른 기존 액션은 이동비 비대상으로 유지한다.
UPDATE strategy_action
SET movement_cost_status = CASE
    WHEN action_type = 'RT_TRANSFER' THEN 'LEGACY_EXCLUDED'
    ELSE 'NOT_APPLICABLE'
END;

ALTER TABLE strategy_action MODIFY (
    movement_cost_status DEFAULT 'NOT_APPLICABLE' NOT NULL
);

ALTER TABLE strategy_action
    ADD CONSTRAINT fk_sa_transfer_route
        FOREIGN KEY (transfer_route_id)
            REFERENCES inventory_transfer_route (transfer_route_id);

ALTER TABLE strategy_action
    ADD CONSTRAINT fk_sa_transfer_cost_policy
        FOREIGN KEY (transfer_cost_policy_id)
            REFERENCES inventory_transfer_cost_policy (transfer_cost_policy_id);

ALTER TABLE strategy_action
    ADD CONSTRAINT ck_sa_movement_cost_status
        CHECK (
            movement_cost_status IN (
                'CALCULATED',
                'NOT_APPLICABLE',
                'LEGACY_EXCLUDED'
            )
        );

ALTER TABLE strategy_action
    ADD CONSTRAINT ck_sa_movement_values
        CHECK (
            (movement_weight_kg IS NULL OR movement_weight_kg > 0)
            AND (movement_distance_km IS NULL OR movement_distance_km > 0)
            AND (movement_cost_per_kg_km IS NULL OR movement_cost_per_kg_km > 0)
            AND (estimated_action_cost IS NULL OR estimated_action_cost >= 0)
        );

ALTER TABLE strategy_action
    ADD CONSTRAINT ck_sa_calculated_movement
        CHECK (
            movement_cost_status <> 'CALCULATED'
            OR (
                action_type = 'RT_TRANSFER'
                AND transfer_route_id IS NOT NULL
                AND transfer_cost_policy_id IS NOT NULL
                AND movement_weight_kg IS NOT NULL
                AND movement_distance_km IS NOT NULL
                AND movement_cost_per_kg_km IS NOT NULL
                AND estimated_action_cost IS NOT NULL
            )
        );

ALTER TABLE strategy_action
    ADD CONSTRAINT ck_sa_noncalculated_movement
        CHECK (
            movement_cost_status = 'CALCULATED'
            OR (
                transfer_route_id IS NULL
                AND transfer_cost_policy_id IS NULL
                AND movement_weight_kg IS NULL
                AND movement_distance_km IS NULL
                AND movement_cost_per_kg_km IS NULL
            )
        );

ALTER TABLE strategy_simulation ADD (
    avoided_holding_cost NUMBER(18,2),
    net_effect           NUMBER(18,2)
);

COMMENT ON TABLE inventory_transfer_route
    IS 'RT_TRANSFER 물리적 출발·도착 위치별 방향성 단방향 이동 경로';

COMMENT ON COLUMN inventory_transfer_route.route_code
    IS '재고 이동 경로 외부 식별 코드';
COMMENT ON COLUMN inventory_transfer_route.source_location_type
    IS '물리적 출발 위치 유형: WAREHOUSE, SALES_POINT';
COMMENT ON COLUMN inventory_transfer_route.destination_location_type
    IS '물리적 도착 위치 유형: WAREHOUSE, SALES_POINT';
COMMENT ON COLUMN inventory_transfer_route.distance_km
    IS '출발지에서 도착지까지의 단방향 도로거리(km)';
COMMENT ON COLUMN inventory_transfer_route.distance_source
    IS '거리 데이터 출처. 개발 더미는 DUMMY, 실제 값은 지도 제공자 또는 MANUAL';
COMMENT ON COLUMN inventory_transfer_route.distance_route_option
    IS '거리 산정 시 사용한 자동차 경로 옵션';
COMMENT ON COLUMN inventory_transfer_route.distance_calculated_at
    IS '도로거리 산정 기준일시';

COMMENT ON TABLE inventory_transfer_cost_policy
    IS 'RT_TRANSFER 중량·거리 기반 예상 이동비 요율 정책';

COMMENT ON COLUMN inventory_transfer_cost_policy.cost_per_kg_km
    IS '재고 1kg을 1km 이동하는 전략 비교용 예상 요율(원/kg·km)';
COMMENT ON COLUMN inventory_transfer_cost_policy.effective_from
    IS '요율 적용 시작일(포함)';
COMMENT ON COLUMN inventory_transfer_cost_policy.effective_to
    IS '요율 적용 종료일(포함), 무기한은 NULL';

COMMENT ON COLUMN strategy_action.transfer_route_id
    IS 'RT_TRANSFER 예상 이동비 계산에 사용한 방향성 경로 ID';
COMMENT ON COLUMN strategy_action.transfer_cost_policy_id
    IS 'RT_TRANSFER 예상 이동비 계산에 사용한 요율 정책 ID';
COMMENT ON COLUMN strategy_action.movement_cost_status
    IS '이동비 계산 상태: CALCULATED, NOT_APPLICABLE, LEGACY_EXCLUDED';
COMMENT ON COLUMN strategy_action.movement_weight_kg
    IS '예상 이동비 계산 당시 총 이동중량(kg) Snapshot';
COMMENT ON COLUMN strategy_action.movement_distance_km
    IS '예상 이동비 계산 당시 단방향 도로거리(km) Snapshot';
COMMENT ON COLUMN strategy_action.movement_cost_per_kg_km
    IS '예상 이동비 계산 당시 적용 요율(원/kg·km) Snapshot';
COMMENT ON COLUMN strategy_action.estimated_action_cost
    IS '전략 액션 예상 비용. RT_TRANSFER는 예상 이동비';

COMMENT ON COLUMN strategy_simulation.movement_cost
    IS '전략에 포함된 RT_TRANSFER 예상 이동비 합계';
COMMENT ON COLUMN strategy_simulation.avoided_disposal_cost
    IS '무전략 대비 절감한 SKU 단위 폐기 처리비 합계';
COMMENT ON COLUMN strategy_simulation.avoided_holding_cost
    IS '무전략 대비 절감한 예상 누적 재고 보관비';
COMMENT ON COLUMN strategy_simulation.net_effect
    IS '공헌이익 증감 + 회피 폐기비 + 회피 보관비 - 전체 액션 비용';
