CREATE TABLE inventory_movement (
                                    inventory_movement_id NUMBER
                                        GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,

                                    inventory_balance_id NUMBER       NOT NULL,
                                    movement_type        VARCHAR2(30) NOT NULL,
                                    movement_qty         NUMBER(15,3) NOT NULL,
                                    before_qty           NUMBER(15,3),
                                    after_qty            NUMBER(15,3),

                                    CONSTRAINT pk_inventory_movement
                                        PRIMARY KEY (inventory_movement_id),

                                    CONSTRAINT fk_inv_movement_balance
                                        FOREIGN KEY (inventory_balance_id)
                                            REFERENCES inventory_balance (inventory_balance_id),

                                    CONSTRAINT ck_inv_movement_type
                                        CHECK (
                                            movement_type IN (
                                                              'INBOUND',
                                                              'SALE',
                                                              'RETURN',
                                                              'TRANSFER_IN',
                                                              'TRANSFER_OUT',
                                                              'DISPOSAL'
                                                )
                                            ),

                                    CONSTRAINT ck_inv_movement_qty
                                        CHECK (movement_qty > 0),

                                    CONSTRAINT ck_inv_movement_before_qty
                                        CHECK (before_qty >= 0),

                                    CONSTRAINT ck_inv_movement_after_qty
                                        CHECK (after_qty >= 0)
);

COMMENT ON TABLE inventory_movement IS
    '재고 변동 이력';

COMMENT ON COLUMN inventory_movement.inventory_movement_id IS
    '재고 변동 이력 ID';

COMMENT ON COLUMN inventory_movement.inventory_balance_id IS
    '변동이 발생한 재고 현황 ID';

COMMENT ON COLUMN inventory_movement.movement_type IS
    '재고 변동 유형: INBOUND, SALE, RETURN, TRANSFER_IN, TRANSFER_OUT, DISPOSAL';

COMMENT ON COLUMN inventory_movement.movement_qty IS
    '재고 변동 수량';

COMMENT ON COLUMN inventory_movement.before_qty IS
    '재고 변동 전 수량';

COMMENT ON COLUMN inventory_movement.after_qty IS
    '재고 변동 후 수량';

CREATE INDEX ix_inv_movement_balance
    ON inventory_movement (inventory_balance_id);